export type BossData = {
  id: string;
  name: string;
  description: string;
  totalHealth: number;
  bossLevel: number;
  imageUrl: string;
};

export const bossesData: BossData[] = [
  {
    id: 'zetsu',
    name: 'Zetsu',
    description: 'O espião da Akatsuki. Capaz de se fundir com o ambiente e criar clones, ele é um mestre da infiltração e da enganação.',
    totalHealth: 2000000,
    bossLevel: 92,
    imageUrl: 'https://i.ibb.co/RTDbjJrX/zetsu.png',
  },
  {
    id: 'hidan',
    name: 'Hidan',
    description: 'O imortal seguidor de Jashin. Qualquer dano que ele recebe é transferido para sua vítima através de um ritual de maldição.',
    totalHealth: 2000000,
    bossLevel: 94,
    imageUrl: 'https://i.ibb.co/PzhBPzjQ/hidan.png',
  },
  {
    id: 'konan',
    name: 'Konan',
    description: 'O "Anjo de Deus" da Akatsuki. Ela pode transformar seu corpo em incontáveis folhas de papel, criando ataques e defesas mortais.',
    totalHealth: 3000000,
    bossLevel: 95,
    imageUrl: 'https://i.ibb.co/215L2g3t/konan.png',
  },
  {
    id: 'deidara',
    name: 'Deidara',
    description: 'O artista terrorista da Akatsuki. Sua argila explosiva toma várias formas, e sua arte final é uma explosão catastrófica.',
    totalHealth: 3000000,
    bossLevel: 96,
    imageUrl: 'https://i.ibb.co/KjgkHnf1/deidara.png',
  },
  {
    id: 'sasori',
    name: 'Sasori da Areia Vermelha',
    description: 'Um mestre de marionetes que transformou a si mesmo em uma.',
    totalHealth: 3000000,
    bossLevel: 96,
    imageUrl: 'https://i.ibb.co/zTnCMG0z/sasori.png',
  },
  {
    id: 'kisame',
    name: 'Kisame Hoshigaki',
    description: 'A "Besta sem Cauda". Com sua espada Samehada, ele pode absorver chakra.',
    totalHealth: 3000000,
    bossLevel: 97,
    imageUrl: 'https://i.ibb.co/WvSbDJqM/kisame.png',
  },
  {
    id: 'tsunade',
    name: 'Tsunade (Quinta Hokage)',
    description: 'Uma dos Sannin Lendários e a maior ninja médica do mundo.',
    totalHealth: 3000000,
    bossLevel: 97,
    imageUrl: 'https://i.ibb.co/Fp3qKBG/tsunade.png',
  },
  {
    id: 'mei',
    name: 'Mei Terumī (Quinta Mizukage)',
    description: 'Mestra de duas Kekkei Genkai.',
    totalHealth: 3000000,
    bossLevel: 97,
    imageUrl: 'https://i.ibb.co/F4s3pNvv/Mei-Terumi.png',
  },
  {
    id: 'onoki',
    name: 'Ōnoki (Terceiro Tsuchikage)',
    description: 'O mestre do Estilo Poeira.',
    totalHealth: 4000000,
    bossLevel: 98,
    imageUrl: 'https://i.ibb.co/60XJsZmp/onoki.png',
  },
  {
    id: 'hiruzen',
    name: 'Hiruzen Sarutobi (Terceiro Hokage)',
    description: 'Conhecido como "O Professor".',
    totalHealth: 4000000,
    bossLevel: 98,
    imageUrl: 'https://i.ibb.co/VcPrNTHj/hiruzen.png',
  },
  {
    id: 'gaara',
    name: 'Gaara (Quinto Kazekage)',
    description: 'Ex-jinchuuriki do Shukaku.',
    totalHealth: 4000000,
    bossLevel: 98,
    imageUrl: 'https://i.ibb.co/1fZppJM4/gaara.png',
  },
  {
    id: 'kakuzu',
    name: 'Kakuzu',
    description: 'O tesoureiro da Akatsuki.',
    totalHealth: 4000000,
    bossLevel: 98,
    imageUrl: 'https://i.ibb.co/zVZ2hqQS/kakuzu.png',
  },
  {
    id: 'ay_fourth',
    name: 'A (Quarto Raikage)',
    description: 'Força e velocidade brutais.',
    totalHealth: 4000000,
    bossLevel: 98,
    imageUrl: 'https://i.ibb.co/ZzWcpG6g/ay-fourth.png',
  },
  {
    id: 'itachi',
    name: 'Itachi Uchiha',
    description: 'Mestre do Sharingan.',
    totalHealth: 4000000,
    bossLevel: 99,
    imageUrl: 'https://i.ibb.co/BpwPzmJ/itachi.png',
  },
  {
    id: 'tobirama',
    name: 'Tobirama Senju',
    description: 'Criador de inúmeros jutsus.',
    totalHealth: 4000000,
    bossLevel: 99,
    imageUrl: 'https://i.ibb.co/mCKKD4ZD/tobirama.png',
  },
  {
    id: 'mu',
    name: 'Mū',
    description: 'O "Não-Humano".',
    totalHealth: 4000000,
    bossLevel: 99,
    imageUrl: 'https://i.ibb.co/PG99PqdB/mu.png',
  },
  {
    id: 'pain',
    name: 'Pain (Caminho Deva)',
    description: 'Portador do Rinnegan.',
    totalHealth: 4500000,
    bossLevel: 100,
    imageUrl: 'https://i.ibb.co/zTtCKZJJ/pain-deva.png',
  },
  {
    id: 'obito_akatsuki',
    name: 'Tobi (Obito Uchiha)',
    description: 'Usuário do Kamui.',
    totalHealth: 4500000,
    bossLevel: 100,
    imageUrl: 'https://i.ibb.co/d0hJ3b1Z/Tobi-Obito-Uchiha.png',
  },
  {
    id: 'minato',
    name: 'Minato Namikaze',
    description: 'O Relâmpago Amarelo de Konoha.',
    totalHealth: 4500000,
    bossLevel: 100,
    imageUrl: 'https://i.ibb.co/Lhb7vmZ6/minato.png',
  },
  {
    id: 'madara_juubi',
    name: 'Madara Uchiha (Jinchūriki)',
    description: 'Forma mais poderosa.',
    totalHealth: 5000000,
    bossLevel: 100,
    imageUrl: 'https://i.ibb.co/zVRqSsmX/Madara-Uchiha-Jinchuriki-do-Dez-Caudas.png',
  },
  {
    id: 'hashirama',
    name: 'Hashirama Senju',
    description: 'O Deus dos Shinobi.',
    totalHealth: 5000000,
    bossLevel: 100,
    imageUrl: 'https://i.ibb.co/dwk6Z521/Hashirama-Senju-Primeiro-Hokage.png',
  },
  {
    id: 'kaguya',
    name: 'Kaguya Ōtsutsuki',
    description: 'A deusa ancestral do chakra.',
    totalHealth: 5500000,
    bossLevel: 100,
    imageUrl: 'https://i.ibb.co/N6dDyCsF/Kaguya-Otsutsuki.png',
  },
];
