export type Mission = {
  id: string;
  name: string;
  description: string;
  difficulty: 'Fácil' | 'Média' | 'Difícil' | 'Heróica';
  requiredLevel: number;
  durationSeconds: number;
  ryoReward: number;
  experienceReward: number;
  chakraCost?: number; // 👈 ADICIONE ESTA LINHA (opcional porque será calculado)
  
  elementExperienceReward?: {
    element: 'Katon' | 'Futon' | 'Raiton' | 'Doton' | 'Suiton';
    xp: number;
  };
  jutsuExperienceReward?: {
    jutsuName: string;
    xp: number;
  };
};

// ========== FUNÇÃO PARA CALCULAR CHAKRA AUTOMATICAMENTE ==========
function calculateMissionChakra(mission: Mission): number {
  // Se já tiver chakraCost definido manualmente, usa ele
  if (mission.chakraCost !== undefined) {
    return mission.chakraCost;
  }

  // Chakra base por dificuldade
  const baseChakra = {
    'Fácil': 20,
    'Média': 50,
    'Difícil': 110,
    'Heróica': 220
  }[mission.difficulty];

  // Ajusta baseado no nível (1% a mais por nível)
  const levelMultiplier = 1 + (mission.requiredLevel / 100);
  let chakraCost = Math.floor(baseChakra * levelMultiplier);

  // Limites por dificuldade (garante valores mínimos e máximos)
  const limits = {
    'Fácil': { min: 10, max: 30 },
    'Média': { min: 35, max: 70 },
    'Difícil': { min: 75, max: 150 },
    'Heróica': { min: 160, max: 300 }
  };

  const { min, max } = limits[mission.difficulty];
  chakraCost = Math.max(min, Math.min(max, chakraCost));

  return chakraCost;
}

export const allJutsus: {name: string, element: string, requiredLevel: number}[] = [
  // ===== KATON (FOGO) =====
  { name: 'Katon: Hōsenka no Jutsu', element: 'Katon', requiredLevel: 1 },
  { name: 'Katon: Gōkakyū no Jutsu', element: 'Katon', requiredLevel: 4 },
  { name: 'Katon: Gōryūka no Jutsu', element: 'Katon', requiredLevel: 6 },
  { name: 'Katon: Haisekishō', element: 'Katon', requiredLevel: 8 },
  { name: 'Katon: Endan', element: 'Katon', requiredLevel: 10 },
  
  // ===== FUTON (VENTO) =====
  { name: 'Futon: Atsugai', element: 'Futon', requiredLevel: 1 },
  { name: 'Futon: Daitoppa', element: 'Futon', requiredLevel: 4 },
  { name: 'Futon: Shinkūha', element: 'Futon', requiredLevel: 6 },
  { name: 'Futon: Rasenshuriken', element: 'Futon', requiredLevel: 8 },
  { name: 'Futon: Shinkū Renpa', element: 'Futon', requiredLevel: 10 },
  
  // ===== RAITON (RAIO) ===== (CORRIGIDOS)
  { name: 'Raiton: Kuroi Panther', element: 'Raiton', requiredLevel: 1 },
  { name: 'Raiton: Raijū Tsuiga', element: 'Raiton', requiredLevel: 4 },
  { name: 'Raiton: Senbon Chidori', element: 'Raiton', requiredLevel: 6 },
  { name: 'Raiton: Liger Bomb', element: 'Raiton', requiredLevel: 8 },
  { name: 'Raiton: Kirin', element: 'Raiton', requiredLevel: 10 },
  
  // ===== DOTON (TERRA) =====
  { name: 'Doton: Arijigoku', element: 'Doton', requiredLevel: 1 },
  { name: 'Doton: Doryūtaiga', element: 'Doton', requiredLevel: 4 },
  { name: 'Doton: Doryūheki', element: 'Doton', requiredLevel: 6 },
  { name: 'Doton: Sando', element: 'Doton', requiredLevel: 8 },
  { name: 'Doton: Doryūdan', element: 'Doton', requiredLevel: 10 },
  
  // ===== SUITON (ÁGUA) =====
  { name: 'Suiton: Bakusui Shōha', element: 'Suiton', requiredLevel: 1 },
  { name: 'Suiton: Daibaku no Jutsu', element: 'Suiton', requiredLevel: 4 },
  { name: 'Suiton: Goshokuzame', element: 'Suiton', requiredLevel: 6 },
  { name: 'Suiton: Suijinheki', element: 'Suiton', requiredLevel: 8 },
  { name: 'Suiton: Suiryūdan no Jutsu', element: 'Suiton', requiredLevel: 10 },
];

const missionsDataRaw: Mission[] = [
  
  // Nível 1-5: Missões de Introdução
  {
    id: 'intro-1',
    name: 'Coleta de Ervas Medicinais',
    description: 'Um farmacêutico local precisa de ervas raras encontradas na floresta perto da aldeia. Cuidado com os animais selvagens.',
    difficulty: 'Fácil',
    requiredLevel: 1,
    durationSeconds: 300, // 5 minutos
    ryoReward: 50,
    experienceReward: 100,
    elementExperienceReward: { element: 'Doton', xp: 20 },
  },
  {
    id: 'intro-2',
    name: 'Entrega de Pergaminho',
    description: 'Leve um pergaminho importante para a aldeia vizinha. A estrada é perigosa, então seja rápido e discreto.',
    difficulty: 'Fácil',
    requiredLevel: 2,
    durationSeconds: 600, // 10 minutos
    ryoReward: 75,
    experienceReward: 120,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 30 },
  },
  {
    id: 'intro-3',
    name: 'Espantalho em Chamas',
    description: 'Alguns corvos estão destruindo as plantações. Use uma técnica Katon para assustá-los sem queimar a colheita.',
    difficulty: 'Fácil',
    requiredLevel: 3,
    durationSeconds: 900, // 15 minutos
    ryoReward: 100,
    experienceReward: 150,
    elementExperienceReward: { element: 'Katon', xp: 50 },
  },
  {
    id: 'intro-4',
    name: 'Purificação do Rio',
    description: 'O rio que abastece a aldeia foi contaminado. Use suas técnicas Suiton para purificar a água.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 1200, // 20 minutos
    ryoReward: 120,
    experienceReward: 180,
    elementExperienceReward: { element: 'Suiton', xp: 60 },
  },
  {
    id: 'intro-5',
    name: 'Velocidade do Vento',
    description: 'Teste sua velocidade e agilidade em um percurso de obstáculos na floresta, usando o vento a seu favor.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1500,
    ryoReward: 150,
    experienceReward: 220,
    elementExperienceReward: { element: 'Futon', xp: 40 },
  },
  {
    id: 'easy-1',
    name: 'Ameaça Elétrica',
    description: 'Uma enguia gigante está dando choques nos pescadores do lago. Use uma técnica Raiton para neutralizá-la.',
    difficulty: 'Fácil',
    requiredLevel: 1,
    durationSeconds: 360, // 6 minutos
    ryoReward: 60,
    experienceReward: 110,
    elementExperienceReward: { element: 'Raiton', xp: 30 },
  },
  {
    id: 'easy-2',
    name: 'Escudo de Terra',
    description: 'Treine suas habilidades defensivas criando pequenas barreiras de terra para bloquear projéteis.',
    difficulty: 'Fácil',
    requiredLevel: 2,
    durationSeconds: 480, // 8 minutos
    ryoReward: 70,
    experienceReward: 115,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 25 },
  },
  {
    id: 'easy-3',
    name: 'Mensagem Urgente',
    description: 'Uma mensagem precisa ser entregue ao posto de vigilância norte o mais rápido possível. A velocidade é essencial.',
    difficulty: 'Fácil',
    requiredLevel: 3,
    durationSeconds: 720, // 12 minutos
    ryoReward: 90,
    experienceReward: 140,
    elementExperienceReward: { element: 'Futon', xp: 40 },
  },
  {
    id: 'easy-4',
    name: 'Projéteis de Água',
    description: 'Pratique seu controle de chakra Suiton acertando alvos em movimento.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 960,
    ryoReward: 110,
    experienceReward: 160,
    elementExperienceReward: { element: 'Suiton', xp: 35 },
  },
  {
    id: 'easy-5',
    name: 'Fogueira para Acampamento',
    description: 'Um grupo de ninjas está acampando e precisa de ajuda para acender uma grande fogueira de forma controlada.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1320, // 22 minutos
    ryoReward: 140,
    experienceReward: 200,
    elementExperienceReward: { element: 'Katon', xp: 65 },
  },
  {
    id: 'easy-6',
    name: 'Treinamento de Taijutsu',
    description: 'Participe de uma sessão de sparring leve para aprimorar seus reflexos e técnicas de combate corpo a corpo.',
    difficulty: 'Fácil',
    requiredLevel: 1,
    durationSeconds: 420, // 7 minutos
    ryoReward: 65,
    experienceReward: 112,
    elementExperienceReward: { element: 'Futon', xp: 25 },
  },
  {
    id: 'easy-7',
    name: 'Afiando a Lâmina de Raio',
    description: 'Concentre seu chakra Raiton para criar uma pequena lâmina e cortar diversos materiais em um dojo de treinamento.',
    difficulty: 'Fácil',
    requiredLevel: 2,
    durationSeconds: 540,
    ryoReward: 80,
    experienceReward: 118,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kuroi Panther', xp: 30 },
  },
  {
    id: 'easy-8',
    name: 'Camuflagem na Floresta',
    description: 'Aprenda técnicas básicas de ocultação, misturando-se com o ambiente para evitar ser detectado.',
    difficulty: 'Fácil',
    requiredLevel: 3,
    durationSeconds: 840, // 14 minutos
    ryoReward: 95,
    experienceReward: 145,
    elementExperienceReward: { element: 'Doton', xp: 45 },
  },
  {
    id: 'easy-9',
    name: 'Controlando a Maré',
    description: 'Ajude os pescadores a trazerem suas redes para a costa usando jutsus Suiton de baixo nível para controlar a correnteza.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 1080, // 18 minutos
    ryoReward: 115,
    experienceReward: 170,
    elementExperienceReward: { element: 'Suiton', xp: 55 },
  },
  {
    id: 'easy-10',
    name: 'Sopro de Cinzas',
    description: 'Crie uma cortina de fumaça usando o Katon: Haisekishō em uma área de treinamento para praticar fugas táticas.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1440, // 24 minutos
    ryoReward: 145,
    experienceReward: 210,
    jutsuExperienceReward: { jutsuName: 'Katon: Haisekishō', xp: 45 },
  },

  // Nível 6-15: Missões de Genin (Média)
  {
    id: 'genin-1',
    name: 'Guarda-costas de um Comerciante',
    description: 'Proteja um comerciante em sua viagem até o próximo posto avançado. Bandidos foram vistos na área.',
    difficulty: 'Média',
    requiredLevel: 6,
    durationSeconds: 1800, // 30 minutos
    ryoReward: 200,
    experienceReward: 300,
    elementExperienceReward: { element: 'Futon', xp: 70 },
  },
    {
    id: 'genin-2',
    name: 'Faísca na Montanha',
    description: 'Uma tempestade se aproxima e você precisa instalar para-raios em pontos estratégicos da montanha. Use Raiton para energizá-los.',
    difficulty: 'Média',
    requiredLevel: 7,
    durationSeconds: 2700, // 45 minutos
    ryoReward: 220,
    experienceReward: 350,
    elementExperienceReward: { element: 'Raiton', xp: 80 },
  },
  {
    id: 'genin-3',
    name: 'Investigação na Caverna',
    description: 'Ruídos estranhos vêm de uma caverna próxima. Investigue a fonte e relate suas descobertas.',
    difficulty: 'Média',
    requiredLevel: 8,
    durationSeconds: 3600,
    ryoReward: 250,
    experienceReward: 400,
    elementExperienceReward: { element: 'Raiton', xp: 50 },
  },
  {
    id: 'genin-4',
    name: 'A Grande Bola de Fogo',
    description: 'Aprenda a controlar um jutsu de fogo mais poderoso para queimar uma barricada de madeira construída por ladrões.',
    difficulty: 'Média',
    requiredLevel: 9,
    durationSeconds: 4500, // 1.25 horas
    ryoReward: 280,
    experienceReward: 450,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōkakyū no Jutsu', xp: 60 },
  },
  {
    id: 'genin-5',
    name: 'Reparo da Ponte',
    description: 'Uma ponte crucial foi danificada. Use suas habilidades Doton para ajudar a reparar a estrutura antes que ela desabe.',
    difficulty: 'Média',
    requiredLevel: 10,
    durationSeconds: 5400, // 1.5 horas
    ryoReward: 300,
    experienceReward: 500,
    elementExperienceReward: { element: 'Doton', xp: 100 },
  },
  {
    id: 'genin-6',
    name: 'Dragão de Água',
    description: 'Um incêndio florestal está fora de controle. Use o Suiton: Suiryūdan no Jutsu para criar um dragão de água e apagar as chamas.',
    difficulty: 'Média',
    requiredLevel: 12,
    durationSeconds: 7200,
    ryoReward: 350,
    experienceReward: 600,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suiryūdan no Jutsu', xp: 70 },
  },
  {
    id: 'medium-1',
    name: 'Corrida nas Árvores',
    description: 'Participe de uma corrida de alta velocidade pelos topos das árvores contra outros genins. Use seu controle de chakra para vencer.',
    difficulty: 'Média',
    requiredLevel: 6,
    durationSeconds: 2100, // 35 minutos
    ryoReward: 210,
    experienceReward: 310,
    elementExperienceReward: { element: 'Futon', xp: 75 },
  },
  {
    id: 'medium-2',
    name: 'Armadilha de Lama',
    description: 'Um grupo de javalis selvagens está atacando viajantes. Crie um atoleiro com Doton: Doryūtaiga para prendê-los.',
    difficulty: 'Média',
    requiredLevel: 7,
    durationSeconds: 3000, // 50 minutos
    ryoReward: 230,
    experienceReward: 360,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūtaiga', xp: 55 },
  },
  {
    id: 'medium-3',
    name: 'Onda de Choque',
    description: 'Dispense uma multidão hostil sem feri-los, usando o Futon: Shinkūha para criar uma onda de choque de ar.',
    difficulty: 'Média',
    requiredLevel: 8,
    durationSeconds: 3900, // 1h 5min
    ryoReward: 260,
    experienceReward: 410,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkūha', xp: 58 },
  },
  {
    id: 'medium-4',
    name: 'Dragão de Fogo',
    description: 'Aprimore seu controle de Katon formando um dragão de fogo para intimidar um grupo de saqueadores.',
    difficulty: 'Média',
    requiredLevel: 9,
    durationSeconds: 4800, // 1h 20min
    ryoReward: 290,
    experienceReward: 460,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōryūka no Jutsu', xp: 62 },
  },
  {
    id: 'medium-5',
    name: 'Escolta Fluvial',
    description: 'Proteja um barco que transporta suprimentos médicos por um rio infestado de piratas. Use jutsus Suiton para controlar o fluxo da água.',
    difficulty: 'Média',
    requiredLevel: 10,
    durationSeconds: 6000, // 1h 40min
    ryoReward: 310,
    experienceReward: 520,
    elementExperienceReward: { element: 'Suiton', xp: 110 },
  },
  {
    id: 'medium-6',
    name: 'Ocultação na Pedra',
    description: 'Aprenda a se fundir com as rochas usando Doton: Sando para espionar um encontro secreto.',
    difficulty: 'Média',
    requiredLevel: 11,
    durationSeconds: 6600, // 1h 50min
    ryoReward: 330,
    experienceReward: 560,
    jutsuExperienceReward: { jutsuName: 'Doton: Sando', xp: 65 },
  },
  {
    id: 'medium-7',
    name: 'Tsunami Local',
    description: 'Uma seca severa atingiu uma área agrícola. Use o Suiton: Daibaku no Jutsu para criar uma onda controlada e irrigar os campos.',
    difficulty: 'Média',
    requiredLevel: 12,
    durationSeconds: 7800,
    ryoReward: 360,
    experienceReward: 620,
    jutsuExperienceReward: { jutsuName: 'Suiton: Daibaku no Jutsu', xp: 75 },
  },
  {
    id: 'medium-8',
    name: 'Lâmina dos Mil Pássaros',
    description: 'Treine a concentração de chakra Raiton na palma da sua mão, aperfeiçoando técnicas avançadas de Raiton.',
    difficulty: 'Média',
    requiredLevel: 13,
    durationSeconds: 9000,
    ryoReward: 400,
    experienceReward: 680,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 80 },
  },
  {
    id: 'medium-9',
    name: 'Prisão Rochosa',
    description: 'Capture um ladrão veloz sem feri-lo, usando o Doton: Arijigoku para criar uma prisão de pilares de pedra ao redor dele.',
    difficulty: 'Média',
    requiredLevel: 14,
    durationSeconds: 10800, // 3 horas
    ryoReward: 450,
    experienceReward: 750,
    jutsuExperienceReward: { jutsuName: 'Doton: Arijigoku', xp: 85 },
  },
  {
    id: 'medium-10',
    name: 'Bombardeio de Fogo',
    description: 'Use o Katon: Endan para lançar uma rajada de bolas de fogo e destruir um acampamento de treinamento inimigo à distância.',
    difficulty: 'Média',
    requiredLevel: 15,
    durationSeconds: 12600, // 3.5 horas
    ryoReward: 480,
    experienceReward: 800,
    jutsuExperienceReward: { jutsuName: 'Katon: Endan', xp: 90 },
  },

  // Nível 16-25: Missões de Chunin (Difícil)
  {
    id: 'chunin-1',
    name: 'Infiltração e Reconhecimento',
    description: 'Infiltre-se em um acampamento de bandidos e colete informações sobre seus planos sem ser detectado.',
    difficulty: 'Difícil',
    requiredLevel: 16,
    durationSeconds: 14400, // 4 horas
    ryoReward: 500,
    experienceReward: 800,
    elementExperienceReward: { element: 'Suiton', xp: 150 },
  },
  {
    id: 'chunin-2',
    name: 'Caça a um Ninja Renegado',
    description: 'Um ninja renegado de baixo escalão foi localizado. Capture-o e traga-o de volta para a aldeia para interrogatório.',
    difficulty: 'Difícil',
    requiredLevel: 18,
    durationSeconds: 21600,
    ryoReward: 700,
    experienceReward: 1000,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 80 },
  },
  {
    id: 'chunin-4',
    name: 'Muralha de Terra Impenetrável',
    description: 'Sua equipe está encurralada. Use o Doton: Doryūheki para criar uma muralha de terra e proteger seus companheiros.',
    difficulty: 'Difícil',
    requiredLevel: 22,
    durationSeconds: 36000, // 10 horas
    ryoReward: 1000,
    experienceReward: 1500,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 120 },
  },
  {
    id: 'difficult-1',
    name: 'Assalto ao Comboio',
    description: 'Intercepte um comboio de suprimentos inimigo que atravessa o País do Fogo. Recupere os suprimentos sem destruí-los.',
    difficulty: 'Difícil',
    requiredLevel: 17,
    durationSeconds: 18000, // 5 horas
    ryoReward: 600,
    experienceReward: 900,
    elementExperienceReward: { element: 'Katon', xp: 160 },
  },
  {
    id: 'difficult-2',
    name: 'O Cortador de Relâmpagos',
    description: 'Um espadachim habilidoso está aterrorizando uma vila. Derrote-o em um duelo, aprimorando seu Raiton: Senbon Chidori.',
    difficulty: 'Difícil',
    requiredLevel: 19,
    durationSeconds: 25200, // 7 horas
    ryoReward: 780,
    experienceReward: 1100,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 110 },
  },
  {
    id: 'difficult-3',
    name: 'Ventos da Purificação',
    description: 'Uma névoa venenosa foi liberada em um vale. Use o Futon: Shinkū Renpa para criar vácuos consecutivos e dispersar o veneno.',
    difficulty: 'Difícil',
    requiredLevel: 21,
    durationSeconds: 32400, // 9 horas
    ryoReward: 920,
    experienceReward: 1350,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkū Renpa', xp: 115 },
  },
  {
    id: 'difficult-4',
    name: 'Bomba do Tubarão de Água',
    description: 'Destrua um portão fortificado usando o Suiton: Suijinheki, um projétil de água com poder de impacto massivo.',
    difficulty: 'Difícil',
    requiredLevel: 23,
    durationSeconds: 39600, // 11 horas
    ryoReward: 1100,
    experienceReward: 1600,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suijinheki', xp: 125 },
  },
  {
    id: 'difficult-5',
    name: 'Resgate Sob Pressão',
    description: 'Um refém importante está sendo mantido em um local prestes a desmoronar. Use suas habilidades para resgatá-lo antes que seja tarde demais.',
    difficulty: 'Difícil',
    requiredLevel: 24,
    durationSeconds: 41400, // 11.5 horas
    ryoReward: 1200,
    experienceReward: 1750,
    elementExperienceReward: { element: 'Doton', xp: 200 },
  },
  {
    id: 'difficult-6',
    name: 'Assassinato Silencioso',
    description: 'Elimine um alvo de alta periculosidade em território inimigo. A discrição é fundamental para o sucesso e sua sobrevivência.',
    difficulty: 'Difícil',
    requiredLevel: 25,
    durationSeconds: 43200, // 12 horas
    ryoReward: 1300,
    experienceReward: 1850,
    elementExperienceReward: { element: 'Futon', xp: 220 },
  },
  {
    id: 'difficult-7',
    name: 'Chuva de Fogo',
    description: 'Dizime uma unidade de infantaria inimiga com uma chuva de pequenas bolas de fogo usando Katon: Hōsenka no Jutsu em grande escala.',
    difficulty: 'Difícil',
    requiredLevel: 16,
    durationSeconds: 16200, // 4.5 horas
    ryoReward: 550,
    experienceReward: 850,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 95 },
  },
  {
    id: 'difficult-8',
    name: 'Campo Minado de Terra',
    description: 'Prepare uma emboscada para uma tropa que se aproxima, criando um campo de armadilhas explosivas de terra.',
    difficulty: 'Difícil',
    requiredLevel: 18,
    durationSeconds: 23400, // 6.5 horas
    ryoReward: 740,
    experienceReward: 1050,
    elementExperienceReward: { element: 'Doton', xp: 180 },
  },
  {
    id: 'difficult-9',
    name: 'Onda Explosiva',
    description: 'Crie uma inundação massiva com Suiton: Bakusui Shōha para varrer as defesas inimigas de um forte costeiro.',
    difficulty: 'Difícil',
    requiredLevel: 24,
    durationSeconds: 42300, // 11.75 horas
    ryoReward: 1150,
    experienceReward: 1680,
    jutsuExperienceReward: { jutsuName: 'Suiton: Bakusui Shōha', xp: 130 },
  },
  {
    id: 'difficult-10',
    name: 'Sabotagem de Linhas de Suprimento',
    description: 'Viaje para o território inimigo e destrua suas linhas de suprimento para enfraquecer seu exército antes de uma grande batalha.',
    difficulty: 'Difícil',
    requiredLevel: 20,
    durationSeconds: 28800, // 8 horas
    ryoReward: 880,
    experienceReward: 1250,
    elementExperienceReward: { element: 'Raiton', xp: 190 },
  },

  // Nível 25+: Missões de Jounin (Heróica)
  {
    id: 'jounin-1',
    name: 'Defesa da Aldeia',
    description: 'Uma onda de ninjas inimigos está se aproximando. Ajude a defender os portões da aldeia a todo custo.',
    difficulty: 'Heróica',
    requiredLevel: 25,
    durationSeconds: 43200, // 12 horas
    ryoReward: 1500,
    experienceReward: 2000,
    elementExperienceReward: { element: 'Raiton', xp: 250 },
  },
  {
    id: 'aniquilacao-rasenshuriken',
    name: 'Aniquilação com Rasenshuriken',
    description: 'Um monstro invocado ameaça uma fortaleza aliada. Domine e use o Futon: Rasenshuriken para desintegrar a ameaça.',
    difficulty: 'Heróica',
    requiredLevel: 30,
    durationSeconds: 86400, // 24 horas
    ryoReward: 2500,
    experienceReward: 3000,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 200 },
  },
  {
    id: 'jounin-3',
    name: 'O Pântano da Morte',
    description: 'Para deter o avanço de um exército, transforme um campo de batalha inteiro em um pântano intransitável com o Doton: Doryūdan.',
    difficulty: 'Heróica',
    requiredLevel: 35,
    durationSeconds: 129600, // 36 horas
    ryoReward: 3500,
    experienceReward: 4000,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 250 },
  },
  {
    id: 'jounin-4',
    name: 'A Chegada de Kirin',
    description: 'Invoque o poder dos céus. Use o Raiton: Kirin para obliterar uma base inimiga inteira com um único e devastador golpe de raio.',
    difficulty: 'Heróica',
    requiredLevel: 40,
    durationSeconds: 172800, // 48 horas
    ryoReward: 5000,
    experienceReward: 5000,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 300 },
  },
  {
    id: 'heroic-1',
    name: 'Caçar um Bijuu',
    description: 'Uma Besta com Cauda foi avistada. Sua missão é rastreá-la e subjugá-la com a ajuda de sua equipe. Falhar não é uma opção.',
    difficulty: 'Heróica',
    requiredLevel: 50,
    durationSeconds: 172800, // 48 horas
    ryoReward: 6000,
    experienceReward: 4500,
    elementExperienceReward: { element: 'Futon', xp: 400 },
  },
  {
    id: 'heroic-2',
    name: 'Enfrentar um Kage',
    description: 'Desafie o Kage de uma aldeia rival para um duelo oficial para resolver uma disputa territorial. A honra da sua aldeia está em jogo.',
    difficulty: 'Heróica',
    requiredLevel: 48,
    durationSeconds: 108000, // 30 horas
    ryoReward: 4000,
    experienceReward: 3500,
    elementExperienceReward: { element: 'Raiton', xp: 350 },
  },
  {
    id: 'guerra-ninja',
    name: 'Parar a Grande Guerra Ninja',
    description: 'Uma guerra em escala mundial está prestes a eclodir. Cumpra uma série de missões críticas para evitar o conflito e salvar inúmeras vidas.',
    difficulty: 'Heróica',
    requiredLevel: 55,
    durationSeconds: 144000, // 40 horas
    ryoReward: 6500,
    experienceReward: 5500,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 280 },
  },
  {
    id: 'heroic-4',
    name: 'Decifrar o Pergaminho Proibido',
    description: 'Um antigo pergaminho contendo jutsus proibidos foi encontrado. Estude-o em segredo para aprender uma técnica ancestral, mas cuidado com seus perigos.',
    difficulty: 'Heróica',
    requiredLevel: 45,
    durationSeconds: 158400, // 44 horas
    ryoReward: 3800,
    experienceReward: 3200,
    elementExperienceReward: { element: 'Suiton', xp: 320 },
  },
  {
    id: 'heroic-5',
    name: 'Sobreviver ao Exame Jounin Final',
    description: 'O teste final para se tornar um Jounin. Enfrente uma série de desafios mortais que testarão seus limites físicos e mentais ao extremo.',
    difficulty: 'Heróica',
    requiredLevel: 42,
    durationSeconds: 172800, // 48 horas
    ryoReward: 7500,
    experienceReward: 7500,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 400 },
  },
  {
    id: 'heroic-6',
    name: 'Proteger o Jinchuuriki',
    description: 'A Akatsuki está caçando o Jinchuuriki da sua aldeia. Sirva como sua guarda pessoal e impeça os ataques da organização a todo custo.',
    difficulty: 'Heróica',
    requiredLevel: 46,
    durationSeconds: 129600, // 36 horas
    ryoReward: 4500,
    experienceReward: 4000,
    elementExperienceReward: { element: 'Doton', xp: 380 },
  },
  {
    id: 'heroic-7',
    name: 'A Invasão de Pain',
    description: 'Os Seis Caminhos de Pain atacam a aldeia. Lute contra os invasores e proteja os cidadãos da destruição total.',
    difficulty: 'Heróica',
    requiredLevel: 52,
    durationSeconds: 172800, // 48 horas
    ryoReward: 8000,
    experienceReward: 7000,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 250 },
  },
  {
    id: 'heroic-8',
    name: 'A Grande Cachoeira da Verdade',
    description: 'Viaje para a lendária cachoeira para confrontar seu eu interior e alcançar um novo patamar de poder e autoconhecimento.',
    difficulty: 'Heróica',
    requiredLevel: 44,
    durationSeconds: 90000, // 25 horas
    ryoReward: 3000,
    experienceReward: 2800,
    elementExperienceReward: { element: 'Suiton', xp: 300 },
  },
  {
    id: 'heroic-9',
    name: 'Reconstruir a Aldeia',
    description: 'Após um ataque devastador, lidere os esforços de reconstrução da aldeia, usando seus jutsus Doton para reerguer as estruturas.',
    difficulty: 'Heróica',
    requiredLevel: 40,
    durationSeconds: 115200, // 32 horas
    ryoReward: 2500,
    experienceReward: 2500,
    elementExperienceReward: { element: 'Doton', xp: 280 },
  },
  {
    id: 'heroic-10',
    name: 'O Legado do Quarto Hokage',
    description: 'Encontre um esconderijo secreto contendo as pesquisas do Quarto Hokage sobre o Hiraishin no Jutsu. Estude e tente replicar a técnica.',
    difficulty: 'Heróica',
    requiredLevel: 60,
    durationSeconds: 172800, // 48 horas
    ryoReward: 10000,
    experienceReward: 9000,
    elementExperienceReward: { element: 'Raiton', xp: 500 },
  },
  {
    id: 'easy-hosenka-1',
    name: 'Festival das Lanternas',
    description: 'Use o Katon: Hōsenka no Jutsu para acender as lanternas de papel do festival da aldeia com pequenas e controladas chamas.',
    difficulty: 'Fácil',
    requiredLevel: 3,
    durationSeconds: 600,
    ryoReward: 80,
    experienceReward: 130,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 40 },
  },
  {
    id: 'easy-hosenka-2',
    name: 'Sinal de Fumaça Colorida',
    description: 'Envie sinais para uma equipe de reconhecimento usando o Hōsenka no Jutsu com pólvoras de cores diferentes.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 900,
    ryoReward: 100,
    experienceReward: 160,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 50 },
  },
  {
    id: 'medium-hosenka-1',
    name: 'Distração Ardente',
    description: 'Crie uma distração para permitir que sua equipe se infiltre, lançando uma saraivada de pequenas bolas de fogo em um ponto estratégico.',
    difficulty: 'Média',
    requiredLevel: 11,
    durationSeconds: 6300,
    ryoReward: 320,
    experienceReward: 540,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 70 },
  },
  {
    id: 'difficult-hosenka-1',
    name: 'Emboscada da Fênix',
    description: 'Prepare uma emboscada para um comboio inimigo, usando o terreno para ocultar-se e atacar com uma chuva de projéteis de fogo no momento certo.',
    difficulty: 'Difícil',
    requiredLevel: 18,
    durationSeconds: 23400,
    ryoReward: 750,
    experienceReward: 1080,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 110 },
  },
  {
    id: 'heroic-hosenka-1',
    name: 'Dança das Mil Flores de Fogo',
    description: 'Enfrente um pelotão de elite em campo aberto, usando a maestria do Hōsenka no Jutsu para criar um espetáculo mortal e inesquivável de chamas.',
    difficulty: 'Heróica',
    requiredLevel: 32,
    durationSeconds: 93600,
    ryoReward: 2800,
    experienceReward: 3200,
    jutsuExperienceReward: { jutsuName: 'Katon: Hōsenka no Jutsu', xp: 220 },
  },
  {
    id: 'easy-gokakyu-1',
    name: 'Aquecendo a Forja',
    description: 'O ferreiro da aldeia precisa de uma fonte de calor intensa e rápida para temperar um novo lote de espadas. Use sua Grande Bola de Fogo para aquecer a forja.',
    difficulty: 'Fácil',
    requiredLevel: 6,
    durationSeconds: 1200,
    ryoReward: 130,
    experienceReward: 190,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōkakyū no Jutsu', xp: 50 }
  },
  {
    id: 'easy-gokakyu-2',
    name: 'Sinalização para o Hokage',
    description: 'Envie um sinal de fogo do topo da Montanha Hokage para alertar sobre uma emergência. O sinal precisa ser grande e visível de longe.',
    difficulty: 'Fácil',
    requiredLevel: 7,
    durationSeconds: 1500,
    ryoReward: 160,
    experienceReward: 230,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōkakyū no Jutsu', xp: 55 }
  },
  {
    id: 'medium-gokakyu-1',
    name: 'Barricada em Chamas',
    description: 'Bandidos bloquearam uma passagem importante com uma barricada de madeira. Destrua-a com uma única e poderosa Bola de Fogo.',
    difficulty: 'Média',
    requiredLevel: 13,
    durationSeconds: 8100,
    ryoReward: 380,
    experienceReward: 650,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōkakyū no Jutsu', xp: 75 }
  },
  {
    id: 'difficult-gokakyu-1',
    name: 'Incinerar o Ninho',
    description: 'Um ninho de insetos gigantes venenosos ameaça a floresta. Use o Katon: Gōkakyū no Jutsu para incinerar o ninho principal à distância.',
    difficulty: 'Difícil',
    requiredLevel: 22,
    durationSeconds: 37800,
    ryoReward: 1050,
    experienceReward: 1550,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōkakyū no Jutsu', xp: 120 }
  },
  {
    id: 'heroic-gokakyu-1',
    name: 'Inferno Contra a Névoa',
    description: 'Um ninja da Névoa de elite está usando um jutsu de ocultação para atacar. Disperse a névoa e revele o inimigo com uma bola de fogo de proporções gigantescas.',
    difficulty: 'Heróica',
    requiredLevel: 38,
    durationSeconds: 151200, // 42 horas
    ryoReward: 4200,
    experienceReward: 4500,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōkakyū no Jutsu', xp: 280 }
  },
  {
    id: 'easy-goryuka-1',
    name: 'Acendendo a Tocha Cerimonial',
    description: 'Use a forma de um dragão de fogo para acender a tocha principal em uma cerimônia da aldeia, impressionando a todos.',
    difficulty: 'Fácil',
    requiredLevel: 8,
    durationSeconds: 1800, // 30 min
    ryoReward: 180,
    experienceReward: 250,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōryūka no Jutsu', xp: 60 }
  },
  {
    id: 'easy-goryuka-2',
    name: 'Espantando Morcegos da Caverna',
    description: 'Uma grande revoada de morcegos tomou conta de uma caverna importante. Use um dragão de fogo para assustá-los e expulsá-los sem causar um desmoronamento.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2100, // 35 min
    ryoReward: 200,
    experienceReward: 280,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōryūka no Jutsu', xp: 65 }
  },
  {
    id: 'medium-goryuka-1',
    name: 'Derretendo o Portão de Gelo',
    description: 'Uma fortaleza inimiga no País da Neve é protegida por um portão de gelo maciço. Use seu Dragão de Fogo para derretê-lo e abrir caminho para a invasão.',
    difficulty: 'Média',
    requiredLevel: 15,
    durationSeconds: 13500, // 3.75 horas
    ryoReward: 500,
    experienceReward: 820,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōryūka no Jutsu', xp: 80 }
  },
  {
    id: 'difficult-goryuka-1',
    name: 'O Dragão Contra a Serpente Gigante',
    description: 'Uma invocação de serpente gigante está causando estragos. Enfrente-a em uma batalha colossal, opondo seu dragão de fogo contra a criatura.',
    difficulty: 'Difícil',
    requiredLevel: 25,
    durationSeconds: 43200, // 12 horas
    ryoReward: 1350,
    experienceReward: 1900,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōryūka no Jutsu', xp: 130 }
  },
  {
    id: 'heroic-goryuka-1',
    name: 'Fúria Dracônica na Fortaleza Voadora',
    description: 'Infiltre-se em uma fortaleza voadora e use múltiplos Dragões de Fogo para sobrecarregar seus motores e derrubá-la dos céus.',
    difficulty: 'Heróica',
    requiredLevel: 42,
    durationSeconds: 172800, // 48 horas
    ryoReward: 7800,
    experienceReward: 7800,
    jutsuExperienceReward: { jutsuName: 'Katon: Gōryūka no Jutsu', xp: 260 }
  },
  {
    id: 'easy-haisekisho-1',
    name: 'Cortina de Fumaça para Fuga',
    description: 'Você foi detectado em uma missão de reconhecimento. Use o Katon: Haisekishō para criar uma densa nuvem de cinzas e escapar sem ser visto.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2400, // 40 min
    ryoReward: 210,
    experienceReward: 300,
    jutsuExperienceReward: { jutsuName: 'Katon: Haisekishō', xp: 60 }
  },
  {
    id: 'easy-haisekisho-2',
    name: 'Sufocando o Fogo',
    description: 'Um pequeno incêndio começou na biblioteca de pergaminhos. Use as cinzas para cortar o oxigênio e apagar o fogo sem danificar os documentos.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 2700, // 45 min
    ryoReward: 230,
    experienceReward: 320,
    jutsuExperienceReward: { jutsuName: 'Katon: Haisekishō', xp: 65 }
  },
  {
    id: 'medium-haisekisho-1',
    name: 'Emboscada de Cinzas',
    description: 'Prepare uma emboscada em uma passagem estreita. Use o Haisekishō para cegar um grupo de mercenários antes de sua equipe atacar.',
    difficulty: 'Média',
    requiredLevel: 16,
    durationSeconds: 15300, // 4.25 horas
    ryoReward: 520,
    experienceReward: 850,
    jutsuExperienceReward: { jutsuName: 'Katon: Haisekishō', xp: 85 }
  },
  {
    id: 'difficult-haisekisho-1',
    name: 'Campo de Batalha Explosivo',
    description: 'Combine suas cinzas com o óleo que um inimigo derramou. Acenda a mistura com uma faísca para criar uma explosão controlada e derrotar um esquadrão inteiro.',
    difficulty: 'Difícil',
    requiredLevel: 26,
    durationSeconds: 46800, // 13 horas
    ryoReward: 1400,
    experienceReward: 2000,
    jutsuExperienceReward: { jutsuName: 'Katon: Haisekishō', xp: 140 }
  },
  {
    id: 'heroic-haisekisho-1',
    name: 'Vulcão de Cinzas',
    description: 'Em um confronto contra um usuário de Doton que ergueu imensas muralhas, libere uma quantidade colossal de cinzas quentes para sufocar e desorientar o inimigo, erodindo suas defesas.',
    difficulty: 'Heróica',
    requiredLevel: 44,
    durationSeconds: 165600, // 46 horas
    ryoReward: 8200,
    experienceReward: 8000,
    jutsuExperienceReward: { jutsuName: 'Katon: Haisekishō', xp: 270 }
  },
  {
    id: 'easy-endan-1',
    name: 'Alvo em Movimento',
    description: 'Pratique sua pontaria com o Katon: Endan acertando alvos de madeira que se movem em uma área de treinamento.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 1800,
    ryoReward: 150,
    experienceReward: 250,
    jutsuExperienceReward: { jutsuName: 'Katon: Endan', xp: 60 }
  },
  {
    id: 'easy-endan-2',
    name: 'Iluminando a Passagem',
    description: 'Uma passagem subterrânea está escura. Use o Endan para criar fontes de luz e guiar sua equipe em segurança.',
    difficulty: 'Fácil',
    requiredLevel: 12,
    durationSeconds: 2400,
    ryoReward: 180,
    experienceReward: 280,
    jutsuExperienceReward: { jutsuName: 'Katon: Endan', xp: 65 }
  },
  {
    id: 'medium-endan-1',
    name: 'Barragem de Fogo',
    description: 'Impeça o avanço de um grupo de ninjas inimigos criando uma barragem contínua de projéteis de fogo com o Endan.',
    difficulty: 'Média',
    requiredLevel: 17,
    durationSeconds: 16200,
    ryoReward: 550,
    experienceReward: 880,
    jutsuExperienceReward: { jutsuName: 'Katon: Endan', xp: 90 }
  },
  {
    id: 'difficult-endan-1',
    name: 'Cerco à Fortaleza',
    description: 'Participe de um cerco, usando o Katon: Endan para bombardear as defesas de uma fortaleza inimiga à distância.',
    difficulty: 'Difícil',
    requiredLevel: 28,
    durationSeconds: 50400,
    ryoReward: 1500,
    experienceReward: 2200,
    jutsuExperienceReward: { jutsuName: 'Katon: Endan', xp: 150 }
  },
  {
    id: 'heroic-endan-1',
    name: 'Chuva de Meteoros',
    description: 'De uma posição elevada, lance uma chuva devastadora de projéteis de fogo sobre o exército inimigo, virando o rumo da batalha.',
    difficulty: 'Heróica',
    requiredLevel: 45,
    durationSeconds: 172800,
    ryoReward: 8500,
    experienceReward: 8200,
    jutsuExperienceReward: { jutsuName: 'Katon: Endan', xp: 300 }
  },
  {
    id: 'easy-shinkugyoku-1',
    name: 'Tiro ao Alvo de Vácuo',
    description: 'Aprimore sua precisão com o Futon: Atsugai, acertando alvos estáticos a diferentes distâncias.',
    difficulty: 'Fácil',
    requiredLevel: 2,
    durationSeconds: 500,
    ryoReward: 75,
    experienceReward: 110,
    jutsuExperienceReward: { jutsuName: 'Futon: Atsugai', xp: 30 }
  },
  {
    id: 'easy-shinkugyoku-2',
    name: 'Limpando o Caminho',
    description: 'Use as Esferas de Vácuo para remover galhos e pequenos obstáculos de uma trilha na floresta, abrindo caminho para uma caravana.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 1000,
    ryoReward: 110,
    experienceReward: 170,
    jutsuExperienceReward: { jutsuName: 'Futon: Atsugai', xp: 45 }
  },
  {
    id: 'medium-shinkugyoku-1',
    name: 'Perfurando a Defesa',
    description: 'Um oponente está usando uma defesa de terra básica. Use o poder perfurante do Shinkūgyoku para quebrá-la.',
    difficulty: 'Média',
    requiredLevel: 14,
    durationSeconds: 10000,
    ryoReward: 420,
    experienceReward: 720,
    jutsuExperienceReward: { jutsuName: 'Futon: Atsugai', xp: 80 }
  },
  {
    id: 'difficult-shinkugyoku-1',
    name: 'Tiro de Longa Distância',
    description: 'Elimine um sentinela em uma torre de vigia a uma grande distância usando uma única e precisa Esfera de Vácuo.',
    difficulty: 'Difícil',
    requiredLevel: 24,
    durationSeconds: 43200,
    ryoReward: 1250,
    experienceReward: 1800,
    jutsuExperienceReward: { jutsuName: 'Futon: Atsugai', xp: 130 }
  },
  {
    id: 'heroic-shinkugyoku-1',
    name: 'Barragem de Vácuo',
    description: 'Enfrente um esquadrão de ninjas voadores, disparando uma barragem de Esferas de Vácuo para derrubá-los dos céus.',
    difficulty: 'Heróica',
    requiredLevel: 40,
    durationSeconds: 162000,
    ryoReward: 7000,
    experienceReward: 7000,
    jutsuExperienceReward: { jutsuName: 'Futon: Atsugai', xp: 250 }
  },
  // Futon: Shinkūha
  {
    id: 'easy-shinkuha-1',
    name: 'Empurrando Obstáculos',
    description: 'Uma avalanche bloqueou uma estrada. Use a onda de vácuo para empurrar as pedras menores e liberar a passagem.',
    difficulty: 'Fácil',
    requiredLevel: 8,
    durationSeconds: 2000,
    ryoReward: 190,
    experienceReward: 260,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkūha', xp: 50 },
  },
  {
    id: 'easy-shinkuha-2',
    name: 'Treinamento de Dispersão',
    description: 'Em um campo de treinamento, pratique dispersar uma formação de bonecos de madeira com uma única onda de vácuo.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2500,
    ryoReward: 220,
    experienceReward: 300,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkūha', xp: 55 },
  },
  {
    id: 'medium-shinkuha-1',
    name: 'Repelir o Ataque',
    description: 'Um grupo de lobos selvagens está atacando. Use a Onda de Vácuo para repeli-los sem causar ferimentos graves.',
    difficulty: 'Média',
    requiredLevel: 15,
    durationSeconds: 12000,
    ryoReward: 460,
    experienceReward: 780,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkūha', xp: 80 },
  },
  {
    id: 'difficult-shinkuha-1',
    name: 'Quebrar a Formação',
    description: 'Uma tropa de ninjas inimigos avança em uma formação disciplinada. Use uma poderosa Onda de Vácuo para quebrar suas linhas e criar o caos.',
    difficulty: 'Difícil',
    requiredLevel: 25,
    durationSeconds: 45000,
    ryoReward: 1350,
    experienceReward: 1900,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkūha', xp: 140 },
  },
  {
    id: 'heroic-shinkuha-1',
    name: 'Onda de Choque Sônica',
    description: 'Enfrente um usuário de genjutsu sonoro. Libere uma Onda de Vácuo tão poderosa que distorce o som, quebrando a ilusão e atordoando o oponente.',
    difficulty: 'Heróica',
    requiredLevel: 41,
    durationSeconds: 170000,
    ryoReward: 7500,
    experienceReward: 7500,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkūha', xp: 260 },
  },
  // Futon: Daitoppa
  {
    id: 'easy-kamaitachi-1',
    name: 'Coletando Frutas Altas',
    description: 'Use a corrente de ar do Kamaitachi para cortar os caules de frutas em árvores muito altas sem danificar a fruta.',
    difficulty: 'Fácil',
    requiredLevel: 6,
    durationSeconds: 1300,
    ryoReward: 130,
    experienceReward: 200,
    jutsuExperienceReward: { jutsuName: 'Futon: Daitoppa', xp: 40 },
  },
  {
    id: 'easy-kamaitachi-2',
    name: 'Desarmando Armadilhas',
    description: 'Uma área de treinamento está cheia de armadilhas de fio. Use o Kamaitachi para cortar os fios à distância com segurança.',
    difficulty: 'Fácil',
    requiredLevel: 7,
    durationSeconds: 1600,
    ryoReward: 170,
    experienceReward: 240,
    jutsuExperienceReward: { jutsuName: 'Futon: Daitoppa', xp: 45 },
  },
  {
    id: 'medium-kamaitachi-1',
    name: 'Defesa contra Projéteis',
    description: 'Um grupo de arqueiros está atacando sua posição. Use as correntes de vento do Kamaitachi para desviar as flechas.',
    difficulty: 'Média',
    requiredLevel: 16,
    durationSeconds: 14000,
    ryoReward: 540,
    experienceReward: 860,
    jutsuExperienceReward: { jutsuName: 'Futon: Daitoppa', xp: 85 },
  },
  {
    id: 'difficult-kamaitachi-1',
    name: 'Dança das Lâminas de Vento',
    description: 'Enfrente um espadachim habilidoso em um duelo, usando o Kamaitachi para criar um turbilhão de ventos cortantes que o desarmam.',
    difficulty: 'Difícil',
    requiredLevel: 26,
    durationSeconds: 48000,
    ryoReward: 1450,
    experienceReward: 2100,
    jutsuExperienceReward: { jutsuName: 'Futon: Daitoppa', xp: 150 },
  },
  {
    id: 'heroic-kamaitachi-1',
    name: 'Tornado da Foice',
    description: 'Cerque um batalhão inimigo com um tornado massivo gerado pelo seu Kamaitachi, causando dano contínuo e desorganizando suas forças.',
    difficulty: 'Heróica',
    requiredLevel: 43,
    durationSeconds: 172000,
    ryoReward: 8000,
    experienceReward: 8000,
    jutsuExperienceReward: { jutsuName: 'Futon: Daitoppa', xp: 270 },
  },
  // Futon: Shinkū Renpa
  {
    id: 'easy-shinkurenpa-1',
    name: 'Destruindo a Pedreira',
    description: 'Uma pedreira precisa ser limpa de grandes rochas instáveis. Use as ondas de vácuo consecutivas para quebrá-las em pedaços menores.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2800,
    ryoReward: 240,
    experienceReward: 330,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkū Renpa', xp: 60 },
  },
  {
    id: 'easy-shinkurenpa-2',
    name: 'Contenção de Incêndio',
    description: 'Um incêndio está se espalhando. Use as Ondas de Vácuo para criar uma barreira de ar, cortando o suprimento de oxigênio do fogo e impedindo seu avanço.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 3200,
    ryoReward: 270,
    experienceReward: 360,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkū Renpa', xp: 65 },
  },
  {
    id: 'medium-shinkurenpa-1',
    name: 'Bombardeio Aéreo',
    description: 'De uma posição elevada, lance uma série de Ondas de Vácuo para destruir o equipamento de cerco de um exército inimigo.',
    difficulty: 'Média',
    requiredLevel: 18,
    durationSeconds: 20000,
    ryoReward: 680,
    experienceReward: 950,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkū Renpa', xp: 95 },
  },
  {
    id: 'difficult-shinkurenpa-1',
    name: 'Contra o Susanoo Imperfeito',
    description: 'Um oponente manifestou as costelas do Susanoo. Use o poder contínuo do Shinkū Renpa para pressionar e rachar sua defesa absoluta.',
    difficulty: 'Difícil',
    requiredLevel: 28,
    durationSeconds: 52000,
    ryoReward: 1550,
    experienceReward: 2300,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkū Renpa', xp: 160 },
  },
  {
    id: 'heroic-shinkurenpa-1',
    name: 'Duelo nos Céus',
    description: 'Enfrente um oponente que domina as artes de voo. Use o Shinkū Renpa para controlar o espaço aéreo, criando zonas de vácuo e rajadas cortantes para derrubá-lo.',
    difficulty: 'Heróica',
    requiredLevel: 46,
    durationSeconds: 172800,
    ryoReward: 8800,
    experienceReward: 8500,
    jutsuExperienceReward: { jutsuName: 'Futon: Shinkū Renpa', xp: 290 },
  },
  // Futon: Rasenshuriken
  {
    id: 'easy-rasenshuriken-1',
    name: 'Modelagem do Vento',
    description: 'Treine a primeira etapa do Rasenshuriken, focando em adicionar o elemento vento ao Rasengan para criar as quatro lâminas iniciais.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 3600,
    ryoReward: 300,
    experienceReward: 400,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 50 },
  },
  {
    id: 'easy-rasenshuriken-2',
    name: 'Corte Preciso',
    description: 'Use uma versão em miniatura do Rasenshuriken para cortar com precisão um alvo de diamante em um laboratório ninja, sem danificar nada ao redor.',
    difficulty: 'Fácil',
    requiredLevel: 12,
    durationSeconds: 4800,
    ryoReward: 350,
    experienceReward: 480,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 55 },
  },
  {
    id: 'medium-rasenshuriken-1',
    name: 'Golpe Celular',
    description: 'Teste o efeito do Rasenshuriken em uma invocação resistente, visando causar dano em nível celular e incapacitá-la.',
    difficulty: 'Média',
    requiredLevel: 22,
    durationSeconds: 35000,
    ryoReward: 980,
    experienceReward: 1400,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 110 },
  },
  {
    id: 'difficult-rasenshuriken-1',
    name: 'Lançamento do Rasenshuriken',
    description: 'Aperfeiçoe a técnica de arremessar o Rasenshuriken, destruindo uma fortaleza inimiga à distância com um único golpe devastador.',
    difficulty: 'Difícil',
    requiredLevel: 32,
    durationSeconds: 90000,
    ryoReward: 2700,
    experienceReward: 3100,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 180 },
  },
  {
    id: 'heroic-rasenshuriken-1',
    name: 'Tempestade de Rasenshurikens',
    description: 'Em um confronto contra múltiplos inimigos poderosos, use clones das sombras para criar e lançar múltiplos Rasenshurikens simultaneamente.',
    difficulty: 'Heróica',
    requiredLevel: 50,
    durationSeconds: 172800,
    ryoReward: 9500,
    experienceReward: 9000,
    jutsuExperienceReward: { jutsuName: 'Futon: Rasenshuriken', xp: 320 },
  },
  // Raiton: Liger Bomb
  {
    id: 'easy-rainoken-1',
    name: 'Corte Energizado',
    description: 'Pratique o corte de objetos simples, como bambu e cordas, usando a Espada de Raio para aprimorar o controle do seu chakra Raiton.',
    difficulty: 'Fácil',
    requiredLevel: 2,
    durationSeconds: 600,
    ryoReward: 85,
    experienceReward: 120,
    jutsuExperienceReward: { jutsuName: 'Raiton: Liger Bomb', xp: 35 },
  },
  {
    id: 'easy-rainoken-2',
    name: 'Iluminando o Caminho',
    description: 'Use o brilho da sua Espada de Raio para navegar por uma caverna escura e perigosa, enquanto se defende de criaturas que vivem na escuridão.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 1100,
    ryoReward: 120,
    experienceReward: 180,
    jutsuExperienceReward: { jutsuName: 'Raiton: Liger Bomb', xp: 40 },
  },
  {
    id: 'medium-rainoken-1',
    name: 'Duelo na Ponte',
    description: 'Enfrente um samurai mercenário em um duelo de espadas em uma ponte estreita. Combine seu taijutsu com a Espada de Raio para vencer.',
    difficulty: 'Média',
    requiredLevel: 13,
    durationSeconds: 9500,
    ryoReward: 410,
    experienceReward: 700,
    jutsuExperienceReward: { jutsuName: 'Raiton: Liger Bomb', xp: 85 },
  },
  {
    id: 'difficult-rainoken-1',
    name: 'Quebrando a Armadura de Chakra',
    description: 'Um ninja inimigo usa uma armadura infundida com chakra que o torna resistente a ataques físicos. Use a Espada de Raio para perfurar sua defesa.',
    difficulty: 'Difícil',
    requiredLevel: 23,
    durationSeconds: 42000,
    ryoReward: 1150,
    experienceReward: 1700,
    jutsuExperienceReward: { jutsuName: 'Raiton: Liger Bomb', xp: 125 },
  },
  {
    id: 'heroic-rainoken-1',
    name: 'A Dança das Mil Lâminas de Trovão',
    description: 'Lute contra um mestre de kenjutsu lendário, movendo-se na velocidade de um relâmpago e desferindo incontáveis golpes com sua Espada de Raio.',
    difficulty: 'Heróica',
    requiredLevel: 39,
    durationSeconds: 160000,
    ryoReward: 6800,
    experienceReward: 6800,
    jutsuExperienceReward: { jutsuName: 'Raiton: Liger Bomb', xp: 240 },
  },
// Novas Missões - Raiton: Raijū Tsuiga
  {
    id: 'easy-jibashi-1',
    name: 'Controle de Pragas Elétrico',
    description: 'Ratos de esgoto estão infestando a aldeia. Use o Raiton: Raijū Tsuiga para paralisá-los e facilitar a captura sem causar danos.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 900,
    ryoReward: 100,
    experienceReward: 160,
    jutsuExperienceReward: { jutsuName: 'Raiton: Raijū Tsuiga', xp: 40 },
  },
  {
    id: 'easy-jibashi-2',
    name: 'Desativando Armadilhas',
    description: 'Um antigo campo de treinamento está cheio de armadilhas elétricas. Use o Jibashi para criar um curto-circuito e desativá-las à distância.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1200,
    ryoReward: 130,
    experienceReward: 200,
    jutsuExperienceReward: { jutsuName: 'Raiton: Raijū Tsuiga', xp: 50 },
  },
  {
    id: 'medium-jibashi-1',
    name: 'Fuga da Prisão',
    description: 'Prisioneiros perigosos escaparam. Use o Jibashi em uma área ampla para paralisar os fugitivos e permitir a recaptura sem combate letal.',
    difficulty: 'Média',
    requiredLevel: 14,
    durationSeconds: 10000,
    ryoReward: 430,
    experienceReward: 720,
    jutsuExperienceReward: { jutsuName: 'Raiton: Raijū Tsuiga', xp: 80 },
  },
  {
    id: 'difficult-jibashi-1',
    name: 'Campo de Batalha Eletrocutado',
    description: 'Para conter o avanço de um pelotão, espalhe seu chakra pelo solo e libere uma onda elétrica contínua para retardar e desorientar os inimigos.',
    difficulty: 'Difícil',
    requiredLevel: 24,
    durationSeconds: 42000,
    ryoReward: 1200,
    experienceReward: 1750,
    jutsuExperienceReward: { jutsuName: 'Raiton: Raijū Tsuiga', xp: 130 },
  },
  {
    id: 'heroic-jibashi-1',
    name: 'Sobrecarga no Colosso',
    description: 'Um golem de pedra gigante ameaça a aldeia. Use o Raiton: Raijū Tsuiga com potência máxima para sobrecarregar seu núcleo de chakra e paralisá-lo permanentemente.',
    difficulty: 'Heróica',
    requiredLevel: 40,
    durationSeconds: 170000,
    ryoReward: 7200,
    experienceReward: 7100,
    jutsuExperienceReward: { jutsuName: 'Raiton: Raijū Tsuiga', xp: 250 },
  },
  // Novas Missões - Raiton: Kuroi Panther
  {
    id: 'easy-chidori-1',
    name: 'Treinamento de Perfuração',
    description: 'Aprenda o básico do Chidori perfurando uma cachoeira. O objetivo é manter a forma do jutsu apesar da força da água.',
    difficulty: 'Fácil',
    requiredLevel: 7,
    durationSeconds: 1800,
    ryoReward: 180,
    experienceReward: 250,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kuroi Panther', xp: 60 },
  },
  {
    id: 'easy-chidori-2',
    name: 'Rompendo a Defesa de Quartzo',
    description: 'Um dojo de treinamento usa paredes de quartzo para testar jutsus. Use seu Chidori para perfurar a parede com um único golpe concentrado.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2700,
    ryoReward: 250,
    experienceReward: 350,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kuroi Panther', xp: 65 },
  },
  {
    id: 'medium-chidori-1',
    name: 'O Som dos Mil Pássaros',
    description: 'Enfrente um ninja do Som que usa ondas sonoras para confundir seus sentidos. Use a velocidade e o som do Chidori para romper suas técnicas e atacar.',
    difficulty: 'Média',
    requiredLevel: 17,
    durationSeconds: 17000,
    ryoReward: 600,
    experienceReward: 900,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kuroi Panther', xp: 90 },
  },
  {
    id: 'difficult-chidori-1',
    name: 'Ataque Relâmpago à Caravana',
    description: 'Uma caravana de suprimentos inimiga é protegida por ninjas com defesas de Doton. Use a velocidade e o poder de perfuração do Chidori para romper suas defesas e capturar a caravana.',
    difficulty: 'Difícil',
    requiredLevel: 27,
    durationSeconds: 50000,
    ryoReward: 1500,
    experienceReward: 2200,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kuroi Panther', xp: 150 },
  },
  {
    id: 'heroic-chidori-1',
    name: 'Duelo Contra o Mestre do Aço',
    description: 'Um samurai lendário possui uma armadura impenetrável. A única maneira de vencê-lo é concentrar todo o seu poder em um Chidori perfeito, visando a única falha em sua armadura.',
    difficulty: 'Heróica',
    requiredLevel: 44,
    durationSeconds: 172800,
    ryoReward: 8400,
    experienceReward: 8100,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kuroi Panther', xp: 280 },
  },
  // Novas Missões - Raiton: Senbon Chidori
  {
    id: 'easy-raikiri-1',
    name: 'Corte Dividido',
    description: 'Aprimore o Raikiri em um treinamento onde você deve cortar um raio ao meio. Esta missão testa sua velocidade e precisão ao extremo.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 3600,
    ryoReward: 320,
    experienceReward: 420,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 70 },
  },
  {
    id: 'easy-raikiri-2',
    name: 'Desarmamento Rápido',
    description: 'Em um sparring, seu oponente é um mestre em armas. Use o Raikiri para cortar suas armas ao meio antes que ele possa atacar.',
    difficulty: 'Fácil',
    requiredLevel: 12,
    durationSeconds: 4800,
    ryoReward: 380,
    experienceReward: 500,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 75 },
  },
  {
    id: 'medium-raikiri-1',
    name: 'Corte Através do Genjutsu',
    description: 'Você está preso em um genjutsu que afeta seus sentidos. Use a concentração pura exigida pelo Raikiri para focar seu chakra e quebrar a ilusão com um golpe poderoso.',
    difficulty: 'Média',
    requiredLevel: 20,
    durationSeconds: 28000,
    ryoReward: 880,
    experienceReward: 1250,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 100 },
  },
  {
    id: 'difficult-raikiri-1',
    name: 'Assassinato do General',
    description: 'Infiltre-se em uma base inimiga fortificada e elimine o general comandante. O Raikiri é a única técnica rápida e silenciosa o suficiente para a missão.',
    difficulty: 'Difícil',
    requiredLevel: 30,
    durationSeconds: 86400,
    ryoReward: 2600,
    experienceReward: 3100,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 170 },
  },
  {
    id: 'heroic-raikiri-1',
    name: 'Raikiri Duplo',
    description: 'Enfrente dois Jounins de elite simultaneamente. Usando clones, você deve dominar a arte de empunhar o Raikiri em ambas as mãos para sobreviver.',
    difficulty: 'Heróica',
    requiredLevel: 47,
    durationSeconds: 172800,
    ryoReward: 9000,
    experienceReward: 8800,
    jutsuExperienceReward: { jutsuName: 'Raiton: Senbon Chidori', xp: 300 },
  },
  // Novas Missões - Raiton: Kirin
  {
    id: 'easy-kirin-1',
    name: 'Manipulando o Clima',
    description: 'Aprenda o básico para criar o Kirin. Sua missão é usar jutsus Katon para aquecer a atmosfera e criar nuvens de tempestade, o primeiro passo para invocar o relâmpago.',
    difficulty: 'Fácil',
    requiredLevel: 15,
    durationSeconds: 10800,
    ryoReward: 500,
    experienceReward: 800,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 80 },
  },
  {
    id: 'easy-kirin-2',
    name: 'Guia do Trovão',
    description: 'Uma tempestade natural está se formando. Pratique guiar um relâmpago natural para um alvo específico no chão usando seu controle de chakra Raiton.',
    difficulty: 'Fácil',
    requiredLevel: 18,
    durationSeconds: 14400,
    ryoReward: 650,
    experienceReward: 950,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 85 },
  },
  {
    id: 'medium-kirin-1',
    name: 'O Julgamento dos Céus',
    description: 'Um criminoso notório se esconde em uma fortaleza de metal que atrai raios. Invoque o Kirin para destruir a fortaleza com um único golpe celestial.',
    difficulty: 'Média',
    requiredLevel: 28,
    durationSeconds: 54000,
    ryoReward: 1600,
    experienceReward: 2400,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 120 },
  },
  {
    id: 'difficult-kirin-1',
    name: 'Kirin contra a Hidra',
    description: 'Uma invocação de hidra aquática parece invencível, pois suas cabeças se regeneram. Use o poder avassalador e instantâneo do Kirin para vaporizar todas as cabeças de uma só vez.',
    difficulty: 'Difícil',
    requiredLevel: 36,
    durationSeconds: 129600,
    ryoReward: 3800,
    experienceReward: 4200,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 200 },
  },
  {
    id: 'heroic-kirin-1',
    name: 'Fúria da Tempestade',
    description: 'Lute contra um usuário de Suiton que transformou o campo de batalha em um oceano. Use essa desvantagem a seu favor, criando a tempestade perfeita para invocar o Kirin e eletrocutar toda a área.',
    difficulty: 'Heróica',
    requiredLevel: 55,
    durationSeconds: 172800,
    ryoReward: 10000,
    experienceReward: 10000,
    jutsuExperienceReward: { jutsuName: 'Raiton: Kirin', xp: 350 },
  },
  // Novas Missões - Doton: Doryūheki
  {
    id: 'easy-doryuheki-1',
    name: 'Defesa contra Bolas de Lama',
    description: 'Em uma área de treinamento, outros genins atacarão com projéteis de lama. Use o Doryūheki para criar muralhas e bloquear todos os ataques.',
    difficulty: 'Fácil',
    requiredLevel: 3,
    durationSeconds: 720,
    ryoReward: 95,
    experienceReward: 150,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 45 },
  },
  {
    id: 'easy-doryuheki-2',
    name: 'Contenção de Javali',
    description: 'Um javali selvagem está furioso. Crie uma muralha de terra rapidamente para bloquear sua investida e proteger os aldeões.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1300,
    ryoReward: 140,
    experienceReward: 210,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 50 },
  },
  {
    id: 'medium-doryuheki-1',
    name: 'Barreira contra Kunais',
    description: 'Durante uma emboscada, proteja um dignitário de uma chuva de kunais, erguendo uma Muralha de Terra no momento exato.',
    difficulty: 'Média',
    requiredLevel: 15,
    durationSeconds: 11000,
    ryoReward: 460,
    experienceReward: 760,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 88 },
  },
  {
    id: 'difficult-doryuheki-1',
    name: 'Labirinto de Terra',
    description: 'Para capturar um grupo de bandidos em uma planície, use múltiplos Doryūhekis para criar um labirinto, encurralando-os e confundindo-os.',
    difficulty: 'Difícil',
    requiredLevel: 25,
    durationSeconds: 44000,
    ryoReward: 1300,
    experienceReward: 1800,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 140 },
  },
  {
    id: 'heroic-doryuheki-1',
    name: 'Fortaleza Impenetrável',
    description: 'Sua equipe está protegendo um artefato valioso. Resista a ondas de ataques inimigos, incluindo jutsus poderosos, mantendo uma Muralha de Terra reforçada com chakra por um longo período.',
    difficulty: 'Heróica',
    requiredLevel: 41,
    durationSeconds: 172800,
    ryoReward: 7600,
    experienceReward: 7500,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūheki', xp: 260 },
  },
// Novas Missões - Doton: Doryūtaiga
  {
    id: 'easy-doryutaiga-1',
    name: 'Irrigação com Lama',
    description: 'Um campo de arroz está seco. Use o Doton: Doryūtaiga para criar um pequeno rio de lama e irrigar a plantação.',
    difficulty: 'Fácil',
    requiredLevel: 7,
    durationSeconds: 1900,
    ryoReward: 185,
    experienceReward: 270,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūtaiga', xp: 50 },
  },
  {
    id: 'easy-doryutaiga-2',
    name: 'Apagando o Fogo',
    description: 'Um incêndio em uma cabana de madeira precisa ser controlado. Desvie um riacho próximo usando o Doryūtaiga para apagar as chamas.',
    difficulty: 'Fácil',
    requiredLevel: 8,
    durationSeconds: 2200,
    ryoReward: 210,
    experienceReward: 300,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūtaiga', xp: 55 },
  },
  {
    id: 'medium-doryutaiga-1',
    name: 'Fuga Lamacenta',
    description: 'Atrase um grupo de ninjas inimigos transformando seu caminho de fuga em um rio torrencial de lama.',
    difficulty: 'Média',
    requiredLevel: 17,
    durationSeconds: 16000,
    ryoReward: 580,
    experienceReward: 890,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūtaiga', xp: 90 },
  },
  {
    id: 'difficult-doryutaiga-1',
    name: 'Inundando o Esconderijo',
    description: 'Um esconderijo de bandidos fica em uma ravina. Use o Doryūtaiga para inundar o local com um rio de lama, forçando-os a sair.',
    difficulty: 'Difícil',
    requiredLevel: 27,
    durationSeconds: 49000,
    ryoReward: 1450,
    experienceReward: 2100,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūtaiga', xp: 145 },
  },
  {
    id: 'heroic-doryutaiga-1',
    name: 'Desviando o Dilúvio',
    description: 'Uma barragem está prestes a romper e inundar uma aldeia. Use o Doton: Doryūtaiga em escala massiva para desviar o curso do rio e salvar todos.',
    difficulty: 'Heróica',
    requiredLevel: 42,
    durationSeconds: 172800,
    ryoReward: 7900,
    experienceReward: 7800,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūtaiga', xp: 270 },
  },
  // Novas Missões - Doton: Sando
  {
    id: 'easy-iwagakure-1',
    name: 'Esconde-esconde Ninja',
    description: 'Participe de um treinamento de furtividade onde você deve usar o Sando para se esconder e não ser encontrado por seus instrutores.',
    difficulty: 'Fácil',
    requiredLevel: 6,
    durationSeconds: 1400,
    ryoReward: 135,
    experienceReward: 205,
    jutsuExperienceReward: { jutsuName: 'Doton: Sando', xp: 45 },
  },
  {
    id: 'easy-iwagakure-2',
    name: 'Observação Silenciosa',
    description: 'Use a Ocultação em Rochas para observar um animal selvagem raro em seu habitat natural sem assustá-lo.',
    difficulty: 'Fácil',
    requiredLevel: 7,
    durationSeconds: 1700,
    ryoReward: 175,
    experienceReward: 250,
    jutsuExperienceReward: { jutsuName: 'Doton: Sando', xp: 50 },
  },
  {
    id: 'medium-iwagakure-1',
    name: 'Espionagem em Território Inimigo',
    description: 'Infiltre-se em um posto avançado inimigo usando o Sando para se mover entre as paredes e coletar informações cruciais.',
    difficulty: 'Média',
    requiredLevel: 16,
    durationSeconds: 15000,
    ryoReward: 530,
    experienceReward: 860,
    jutsuExperienceReward: { jutsuName: 'Doton: Sando', xp: 90 },
  },
  {
    id: 'difficult-iwagakure-1',
    name: 'Sabotagem Interna',
    description: 'Entre em uma base inimiga subterrânea, movendo-se pelas paredes para plantar selos explosivos em pontos estratégicos sem ser detectado.',
    difficulty: 'Difícil',
    requiredLevel: 26,
    durationSeconds: 47000,
    ryoReward: 1420,
    experienceReward: 2050,
    jutsuExperienceReward: { jutsuName: 'Doton: Sando', xp: 145 },
  },
  {
    id: 'heroic-iwagakure-1',
    name: 'O Fantasma da Montanha',
    description: 'Um Kage está protegido no coração de sua fortaleza na montanha. Use a maestria do Sando para atravessar defesas impenetráveis e chegar até seu alvo.',
    difficulty: 'Heróica',
    requiredLevel: 43,
    durationSeconds: 171000,
    ryoReward: 8100,
    experienceReward: 7900,
    jutsuExperienceReward: { jutsuName: 'Doton: Sando', xp: 275 },
  },
  // Novas Missões - Doton: Arijigoku
  {
    id: 'easy-ganchuro-1',
    name: 'Cercado de Treinamento',
    description: 'Pratique a criação de jaulas de pedra para prender bonecos de treinamento em movimento.',
    difficulty: 'Fácil',
    requiredLevel: 8,
    durationSeconds: 2100,
    ryoReward: 200,
    experienceReward: 290,
    jutsuExperienceReward: { jutsuName: 'Doton: Arijigoku', xp: 55 },
  },
  {
    id: 'easy-ganchuro-2',
    name: 'Contendo os Animais da Fazenda',
    description: 'Os animais de uma fazenda escaparam. Use a Prisão de Pilares de Pedra para criar cercados temporários e capturá-los.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2600,
    ryoReward: 230,
    experienceReward: 320,
    jutsuExperienceReward: { jutsuName: 'Doton: Arijigoku', xp: 60 },
  },
  {
    id: 'medium-ganchuro-1',
    name: 'Captura, Não Abate',
    description: 'Um ninja renegado precisa ser capturado vivo para interrogatório. Use a Prisão de Pilares de Pedra para imobilizá-lo sem causar dano letal.',
    difficulty: 'Média',
    requiredLevel: 18,
    durationSeconds: 19000,
    ryoReward: 650,
    experienceReward: 920,
    jutsuExperienceReward: { jutsuName: 'Doton: Arijigoku', xp: 95 },
  },
  {
    id: 'difficult-ganchuro-1',
    name: 'Dividir e Conquistar',
    description: 'Enfrente um esquadrão inimigo. Use o Ganchūrō no Jutsu para separar os membros do grupo, prendendo-os em jaulas individuais para que possam ser derrotados um a um.',
    difficulty: 'Difícil',
    requiredLevel: 28,
    durationSeconds: 51000,
    ryoReward: 1520,
    experienceReward: 2250,
    jutsuExperienceReward: { jutsuName: 'Doton: Arijigoku', xp: 155 },
  },
  {
    id: 'heroic-ganchuro-1',
    name: 'Prisão da Besta',
    description: 'Uma besta invocada está fora de controle. Coordene com sua equipe para criar uma prisão de pilares de pedra gigantesca e reforçada com chakra para conter a criatura.',
    difficulty: 'Heróica',
    requiredLevel: 45,
    durationSeconds: 172800,
    ryoReward: 8600,
    experienceReward: 8300,
    jutsuExperienceReward: { jutsuName: 'Doton: Arijigoku', xp: 285 },
  },
  // Novas Missões - Doton: Doryūdan
  {
    id: 'easy-yominuma-1',
    name: 'Pântano de Treino',
    description: 'Transforme uma pequena área de terra em um pântano para praticar o controle sobre a consistência e a profundidade do jutsu.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 3500,
    ryoReward: 290,
    experienceReward: 390,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 65 },
  },
  {
    id: 'easy-yominuma-2',
    name: 'Armadilha para Javalis',
    description: 'Javalis selvagens estão destruindo plantações. Crie um pequeno pântano no caminho deles para atolá-los e impedir que avancem.',
    difficulty: 'Fácil',
    requiredLevel: 11,
    durationSeconds: 4000,
    ryoReward: 330,
    experienceReward: 440,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 70 },
  },
  {
    id: 'medium-yominuma-1',
    name: 'Retirada Tática',
    description: 'Sua equipe está em menor número e precisa recuar. Crie um Pântano do Submundo para cobrir sua retirada e atrasar os perseguidores.',
    difficulty: 'Média',
    requiredLevel: 21,
    durationSeconds: 31000,
    ryoReward: 900,
    experienceReward: 1300,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 105 },
  },
  {
    id: 'difficult-yominuma-1',
    name: 'Afundando a Artilharia',
    description: 'Um exército inimigo está montando catapultas para atacar a aldeia. Transforme o solo sob o equipamento de cerco em um pântano para afundá-lo antes que possa ser usado.',
    difficulty: 'Difícil',
    requiredLevel: 31,
    durationSeconds: 88000,
    ryoReward: 2650,
    experienceReward: 3150,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 175 },
  },
  {
    id: 'heroic-yominuma-1',
    name: 'Mar de Lama',
    description: 'Para deter o avanço de um exército inteiro em um vale, use todo o seu chakra para transformar o vale inteiro em um gigantesco e intransitável Pântano do Submundo.',
    difficulty: 'Heróica',
    requiredLevel: 48,
    durationSeconds: 172800,
    ryoReward: 9200,
    experienceReward: 8900,
    jutsuExperienceReward: { jutsuName: 'Doton: Doryūdan', xp: 310 },
  },
  // Novas Missões - Suiton: Goshokuzame
  {
    id: 'easy-teppodama-1',
    name: 'Apagando Velas',
    description: 'Em um dojo, pratique a precisão do Teppōdama apagando a chama de velas à distância sem derrubá-las.',
    difficulty: 'Fácil',
    requiredLevel: 4,
    durationSeconds: 900,
    ryoReward: 105,
    experienceReward: 165,
    jutsuExperienceReward: { jutsuName: 'Suiton: Goshokuzame', xp: 45 },
  },
  {
    id: 'easy-teppodama-2',
    name: 'Limpando o Alvo',
    description: 'Use os projéteis de água para limpar a sujeira e a ferrugem de alvos de metal em uma área de treinamento.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1100,
    ryoReward: 125,
    experienceReward: 190,
    jutsuExperienceReward: { jutsuName: 'Suiton: Goshokuzame', xp: 50 },
  },
  {
    id: 'medium-teppodama-1',
    name: 'Duelo no Riacho',
    description: 'Enfrente outro ninja usuário de Suiton em um duelo onde apenas o Teppōdama é permitido. Mostre sua superioridade em poder e precisão.',
    difficulty: 'Média',
    requiredLevel: 13,
    durationSeconds: 8500,
    ryoReward: 390,
    experienceReward: 670,
    jutsuExperienceReward: { jutsuName: 'Suiton: Goshokuzame', xp: 80 },
  },
  {
    id: 'difficult-teppodama-1',
    name: 'Bombardeio Naval',
    description: 'De um barco, use o Teppōdama para atacar um navio pirata, visando seus mastros e velas para imobilizá-lo.',
    difficulty: 'Difícil',
    requiredLevel: 23,
    durationSeconds: 40000,
    ryoReward: 1120,
    experienceReward: 1650,
    jutsuExperienceReward: { jutsuName: 'Suiton: Goshokuzame', xp: 120 },
  },
  {
    id: 'heroic-teppodama-1',
    name: 'Chuva de Projéteis',
    description: 'Enfrente um usuário de Katon que lança uma chuva de fogo. Intercepte cada projétil de fogo com um projétil de água, mostrando um domínio perfeito do Teppōdama.',
    difficulty: 'Heróica',
    requiredLevel: 38,
    durationSeconds: 155000,
    ryoReward: 6500,
    experienceReward: 6600,
    jutsuExperienceReward: { jutsuName: 'Suiton: Goshokuzame', xp: 230 },
  },
  // Suiton: Suiryūdan
  {
    id: 'easy-suiryudan-1',
    name: 'Controle do Dragão Aquático',
    description: 'Pratique a formação e a manutenção do Dragão de Água em um lago local, focando em manter sua forma o maior tempo possível.',
    difficulty: 'Fácil',
    requiredLevel: 5,
    durationSeconds: 1400,
    ryoReward: 145,
    experienceReward: 215,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suiryūdan', xp: 55 }
  },
  {
    id: 'easy-suiryudan-2',
    name: 'Apagando a Fogueira',
    description: 'Uma fogueira de acampamento saiu de controle. Use o Suiryūdan para extinguir as chamas com precisão e evitar um incêndio florestal.',
    difficulty: 'Fácil',
    requiredLevel: 7,
    durationSeconds: 1900,
    ryoReward: 190,
    experienceReward: 280,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suiryūdan', xp: 60 }
  },
  {
    id: 'medium-suiryudan-1',
    name: 'Defesa contra Incendiários',
    description: 'Ninjas incendiários estão atacando um portão da aldeia. Proteja a estrutura de madeira interceptando as bolas de fogo com seu Dragão de Água.',
    difficulty: 'Média',
    requiredLevel: 14,
    durationSeconds: 11500,
    ryoReward: 470,
    experienceReward: 780,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suiryūdan', xp: 85 }
  },
  {
    id: 'difficult-suiryudan-1',
    name: 'Combate Naval',
    description: 'Enfrente um navio pirata em alto mar. Use o Suiryūdan para destruir seus canhões, mastros e causar inundações no convés.',
    difficulty: 'Difícil',
    requiredLevel: 24,
    durationSeconds: 43500,
    ryoReward: 1250,
    experienceReward: 1850,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suiryūdan', xp: 140 }
  },
  {
    id: 'heroic-suiryudan-1',
    name: 'Dragão de Água vs Dragão de Fogo',
    description: 'Um mestre em Katon está destruindo uma floresta com seu Katon: Gōryūka no Jutsu. Lute em uma batalha elemental de dragões para proteger a natureza.',
    difficulty: 'Heróica',
    requiredLevel: 40,
    durationSeconds: 172800,
    ryoReward: 7400,
    experienceReward: 7300,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suiryūdan', xp: 260 }
  },
  // Suiton: Daibaku no Jutsu
  {
    id: 'easy-daibakufu-1',
    name: 'Criando Corredeiras',
    description: 'Aprenda a controlar o poder da Grande Cachoeira criando pequenas corredeiras em um rio para treinar seu equilíbrio e controle de chakra.',
    difficulty: 'Fácil',
    requiredLevel: 8,
    durationSeconds: 2300,
    ryoReward: 220,
    experienceReward: 310,
    jutsuExperienceReward: { jutsuName: 'Suiton: Daibaku no Jutsu', xp: 60 }
  },
  {
    id: 'easy-daibakufu-2',
    name: 'Limpando a Encosta',
    description: 'Um deslizamento de terra bloqueou um caminho. Use uma onda controlada do Daibaku para limpar os detritos e reabrir a estrada.',
    difficulty: 'Fácil',
    requiredLevel: 10,
    durationSeconds: 3400,
    ryoReward: 280,
    experienceReward: 380,
    jutsuExperienceReward: { jutsuName: 'Suiton: Daibaku no Jutsu', xp: 65 }
  },
  {
    id: 'medium-daibakufu-1',
    name: 'Repelindo Invasores Aquáticos',
    description: 'Piratas estão tentando desembarcar em uma praia para saquear uma vila. Crie uma grande onda com o Daibaku para empurrar seus barcos de volta para o mar.',
    difficulty: 'Média',
    requiredLevel: 18,
    durationSeconds: 21000,
    ryoReward: 700,
    experienceReward: 1000,
    jutsuExperienceReward: { jutsuName: 'Suiton: Daibaku no Jutsu', xp: 95 }
  },
  {
    id: 'difficult-daibakufu-1',
    name: 'Inundação Estratégica',
    description: 'Um exército inimigo está acampado em um vale seco. Desvie um rio próximo e use o Jutsu da Grande Cachoeira para inundar o acampamento e forçar a rendição.',
    difficulty: 'Difícil',
    requiredLevel: 29,
    durationSeconds: 60000,
    ryoReward: 1800,
    experienceReward: 2500,
    jutsuExperienceReward: { jutsuName: 'Suiton: Daibaku no Jutsu', xp: 160 }
  },
  {
    id: 'heroic-daibakufu-1',
    name: 'Tsunami Devastador',
    description: 'Uma frota naval inimiga se aproxima da costa. Do topo de um penhasco, invoque uma onda gigantesca, um verdadeiro tsunami, para aniquilar a frota inteira.',
    difficulty: 'Heróica',
    requiredLevel: 46,
    durationSeconds: 172800,
    ryoReward: 8900,
    experienceReward: 8600,
    jutsuExperienceReward: { jutsuName: 'Suiton: Daibaku no Jutsu', xp: 290 }
  },
  // Suiton: Suijinheki
  {
    id: 'easy-suikodan-1',
    name: 'Pesca com Tubarão',
    description: 'Impressione os pescadores locais usando um pequeno Projétil de Tubarão para agrupar os peixes em um só lugar, facilitando a pesca.',
    difficulty: 'Fácil',
    requiredLevel: 9,
    durationSeconds: 2800,
    ryoReward: 250,
    experienceReward: 340,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suijinheki', xp: 60 }
  },
  {
    id: 'easy-suikodan-2',
    name: 'Corrida de Tubarões',
    description: 'Participe de uma competição amigável para ver quem consegue guiar um Projétil de Tubarão através de um percurso de obstáculos em um lago mais rápido.',
    difficulty: 'Fácil',
    requiredLevel: 11,
    durationSeconds: 4200,
    ryoReward: 340,
    experienceReward: 460,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suijinheki', xp: 70 }
  },
  {
    id: 'medium-suikodan-1',
    name: 'Caça ao Contrabandista',
    description: 'Um contrabandista está fugindo em um barco rápido. Use o Suikōdan para perseguir e abalroar o barco, forçando-o a parar.',
    difficulty: 'Média',
    requiredLevel: 19,
    durationSeconds: 25000,
    ryoReward: 800,
    experienceReward: 1150,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suijinheki', xp: 98 }
  },
  {
    id: 'difficult-suikodan-1',
    name: 'Tubarões contra a Muralha',
    description: 'Um inimigo se protege atrás de uma muralha de terra. Use múltiplos Projéteis de Tubarão para erodir e destruir a base da muralha, derrubando-a.',
    difficulty: 'Difícil',
    requiredLevel: 30,
    durationSeconds: 88000,
    ryoReward: 2700,
    experienceReward: 3150,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suijinheki', xp: 170 }
  },
  {
    id: 'heroic-suikodan-1',
    name: 'Frenesi dos Cinco Tubarões',
    description: 'Enfrente um monstro marinho gigante. Invoque a técnica dos Cinco Tubarões Famintos para atacar a criatura de múltiplos ângulos, mordendo e rasgando até a submissão.',
    difficulty: 'Heróica',
    requiredLevel: 47,
    durationSeconds: 172800,
    ryoReward: 9100,
    experienceReward: 8900,
    jutsuExperienceReward: { jutsuName: 'Suiton: Suijinheki', xp: 310 }
  },
  // Suiton: Bakusui Shōha
  {
    id: 'easy-bakusuishoha-1',
    name: 'Enchendo o Reservatório',
    description: 'O reservatório de água da aldeia está perigosamente baixo. Use uma versão controlada do Bakusui Shōha para expelir uma grande quantidade de água e reabastecê-lo.',
    difficulty: 'Fácil',
    requiredLevel: 11,
    durationSeconds: 4500,
    ryoReward: 350,
    experienceReward: 470,
    jutsuExperienceReward: { jutsuName: 'Suiton: Bakusui Shōha', xp: 75 }
  },
  {
    id: 'easy-bakusuishoha-2',
    name: 'Criando um Lago Temporário',
    description: 'Para um exercício de treinamento, crie um lago temporário em uma área designada, aprendendo a controlar a quantidade de água expelida.',
    difficulty: 'Fácil',
    requiredLevel: 13,
    durationSeconds: 7000,
    ryoReward: 400,
    experienceReward: 550,
    jutsuExperienceReward: { jutsuName: 'Suiton: Bakusui Shōha', xp: 80 }
  },
  {
    id: 'medium-bakusuishoha-1',
    name: 'Vantagem no Campo de Batalha',
    description: 'Você está lutando em um deserto contra um especialista em Doton. Use o Bakusui Shōha para transformar o campo de batalha arenoso em um lago, ganhando vantagem elemental.',
    difficulty: 'Média',
    requiredLevel: 22,
    durationSeconds: 34000,
    ryoReward: 950,
    experienceReward: 1350,
    jutsuExperienceReward: { jutsuName: 'Suiton: Bakusui Shōha', xp: 110 }
  },
  {
    id: 'difficult-bakusuishoha-1',
    name: 'Fuga da Prisão Subterrânea',
    description: 'Você foi capturado e está em uma prisão subterrânea. Use a Onda de Colisão Explosiva para inundar completamente a base e criar uma rota de fuga.',
    difficulty: 'Difícil',
    requiredLevel: 33,
    durationSeconds: 100000,
    ryoReward: 3000,
    experienceReward: 3500,
    jutsuExperienceReward: { jutsuName: 'Suiton: Bakusui Shōha', xp: 190 }
  },
  {
    id: 'heroic-bakusuishoha-1',
    name: 'O Oceano Pessoal',
    description: 'Lute contra uma invocação lendária do tamanho de uma montanha. Libere todo o seu chakra para criar um oceano inteiro com o Bakusui Shōha, submergindo o inimigo e preparando o terreno para seus outros jutsus Suiton.',
    difficulty: 'Heróica',
    requiredLevel: 50,
    durationSeconds: 172800,
    ryoReward: 9600,
    experienceReward: 9200,
    jutsuExperienceReward: { jutsuName: 'Suiton: Bakusui Shōha', xp: 330 }
  },
];
// ========== PROCESSA TODAS AS MISSÕES COM CHAKRA ==========
export const missionsData = missionsDataRaw.map(mission => ({
  ...mission,
  chakraCost: calculateMissionChakra(mission)
}));