import { BuildType } from '@/lib/battle-system/build-detector';

export type SummonBuildAbility = {
  name: string;
  description: string;
  emoji: string;
  effectType:
    | 'stat_bonus'
    | 'battle_passive'
    | 'turn_effect'
    | 'aura';
  value?: number;
  targetStat?: 'taijutsu' | 'ninjutsu' | 'genjutsu' | 'selo' | 'vitalidade' | 'inteligencia' | 'hp' | 'chakra';
};

export type Summon = {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  buffs: {
    taijutsu: number;
    ninjutsu: number;
    genjutsu: number;
    selo: number;
    vitalidade: number;
    inteligencia: number;
  };
  requiredLevel: number;
  price: number;
  trainableStats: string[];
  isPremium?: boolean;
  buildAbilities: Partial<Record<BuildType, SummonBuildAbility>>;
};

function ab(
  name: string, description: string, emoji: string,
  effectType: SummonBuildAbility['effectType'],
  value?: number, targetStat?: SummonBuildAbility['targetStat']
): SummonBuildAbility {
  return { name, description, emoji, effectType, value, targetStat };
}

export const summonsData: Summon[] = [
  {
    id: 'ton-ton', name: 'Tonton',
    description: 'A porquinha de estimação de Tsunade e Shizune. Apesar de pequena, tem um olfato apurado.',
    imageUrl: 'https://i.ibb.co/Zz5hpX5D/tonton.png',
    buffs: { taijutsu: 0, ninjutsu: 0, genjutsu: 0, selo: 5, vitalidade: 1, inteligencia: 2 },
    requiredLevel: 1, price: 100, trainableStats: ['selo', 'vitalidade', 'inteligencia'],
    buildAbilities: {
      berserker:       ab('Faro de Caça',        'Primeiro ataque +20% dano',                               '⚔️', 'battle_passive', 0.20),
      sombra:          ab('Olfato Sombrio',       '+10% dano em todos os tipos',                             '🌑', 'aura', 0.10),
      ilusionista:     ab('Pista Falsa',          'Primeiro genjutsu tem 100% de chance de acertar',         '🎭', 'battle_passive'),
      tanque:          ab('Escudo Oink',          'Redução de dano recebido +5%',                            '🛡️', 'battle_passive', 0.05),
      fisico_sabio:    ab('Análise Tática',       '+8% dano de taijutsu via inteligência',                   '🧠', 'stat_bonus', 0.08, 'taijutsu'),
      artes_proibidas: ab('Marca Cheirosa',       'Genjutsu aplica fraqueza +5% adicional',                  '🔮', 'battle_passive', 0.05),
      feiticeiro:      ab('Farejador Mágico',     'Próximo ninjutsu após defesa +15% dano',                  '✨', 'turn_effect', 0.15),
      guardiao:        ab('Aura Curativa',         'Regen passiva +1% HP por turno',                         '🌊', 'aura', 0.01, 'hp'),
      oraculo:         ab('Intuição Animal',       '+10% no elemento com maior nível',                       '🔯', 'battle_passive', 0.10),
      fantasma:        ab('Rastro Invisível',      'Genjutsu ignora 15% da resistência do alvo',             '👻', 'battle_passive', 0.15),
      monge:           ab('Paz Interior',          'Redução de dano de genjutsu recebido +8%',               '🧘', 'battle_passive', 0.08),
      imortal:         ab('Instinto de Sobrevivência', '+5% chance de sobreviver com 1 HP extra',            '💀', 'battle_passive', 0.05),
      senhor_guerra:   ab('Grunhido de Guerra',   '+1% crítico para cada 50 pts de vitalidade',             '🏆', 'battle_passive'),
      protetor:        ab('Aura Protetora',         'Todos os danos recebidos -4%',                          '🏯', 'aura', 0.04),
      ermitao:         ab('Silêncio do Rastreador','Primeiro ataque é sempre crítico',                       '🌙', 'battle_passive'),
      generico:        ab('Olfato Aguçado',         '+5 pontos de selo',                                     '🐷', 'stat_bonus', 5, 'selo'),
    },
  },
  {
    id: 'akamaru', name: 'Akamaru',
    description: 'O fiel companheiro canino de Kiba Inuzuka.',
    imageUrl: 'https://i.ibb.co/7xskt10S/akamaru.png',
    buffs: { taijutsu: 5, ninjutsu: 0, genjutsu: 0, selo: 2, vitalidade: 5, inteligencia: 0 },
    requiredLevel: 5, price: 500, trainableStats: ['taijutsu', 'selo', 'vitalidade'],
    buildAbilities: {
      berserker:       ab('Garras Furiosas',   '+15% dano de taijutsu em estado crítico',           '⚔️', 'battle_passive', 0.15, 'taijutsu'),
      sombra:          ab('Duo Sombrio',        'Segundo hit do Ataque Duplo +10% dano',             '🌑', 'battle_passive', 0.10),
      ilusionista:     ab('Distração Uivante', 'Genjutsu falho reduz cooldown em 1 turno',           '🎭', 'battle_passive'),
      tanque:          ab('Pelagem Resistente','HP máximo +8%',                                      '🛡️', 'stat_bonus', 0.08, 'hp'),
      fisico_sabio:    ab('Faro Estratégico',  '+12% dano de taijutsu acima de 70% HP',              '🧠', 'battle_passive', 0.12),
      artes_proibidas: ab('Latido Sombrio',    '30% de chance de anular defesa do oponente',         '🔮', 'battle_passive', 0.30),
      feiticeiro:      ab('Energia Selvagem',  '+10% ao jutsuMultiplier',                            '✨', 'battle_passive', 0.10),
      guardiao:        ab('Lealdade Infinita', 'Regen +2% HP ao receber ataque crítico',             '🌊', 'turn_effect', 0.02, 'hp'),
      oraculo:         ab('Instinto Elemental','+15% dano no elemento principal',                    '🔯', 'battle_passive', 0.15),
      fantasma:        ab('Latido Espectral',  '20% chance de paralisia ao acertar genjutsu',        '👻', 'battle_passive', 0.20),
      monge:           ab('Companheirismo',    'Redução de dano geral +6%',                          '🧘', 'battle_passive', 0.06),
      imortal:         ab('Vontade de Lutar', 'Sobreviver à morte regenera 5% HP',                   '💀', 'turn_effect', 0.05, 'hp'),
      senhor_guerra:   ab('Bravura Canina',   'Vitalidade dá +1.5% crítico a cada 100 pts',          '🏆', 'battle_passive'),
      protetor:        ab('Guarda Fiel',       'Reduz todo dano recebido -6%',                       '🏯', 'aura', 0.06),
      ermitao:         ab('Caçada Silenciosa', 'Primeiro ataque ignora cap de 35%',                  '🌙', 'battle_passive'),
      generico:        ab('Companheiro Leal',  '+5 taijutsu',                                        '🐕', 'stat_bonus', 5, 'taijutsu'),
    },
  },
  {
    id: 'pakkun', name: 'Pakkun',
    description: 'O líder dos Ninken de Kakashi.',
    imageUrl: 'https://i.ibb.co/fdgChM9c/pakkun.png',
    buffs: { taijutsu: 0, ninjutsu: 0, genjutsu: 0, selo: 10, vitalidade: 0, inteligencia: 10 },
    requiredLevel: 10, price: 1500, trainableStats: ['selo', 'inteligencia'],
    buildAbilities: {
      berserker:       ab('Rastreamento Crítico', 'Chance de crítico +8%',                             '⚔️', 'battle_passive', 0.08),
      sombra:          ab('Estratégia Dupla',     'Ataque Duplo tem +10% de chance de ativar',          '🌑', 'battle_passive', 0.10),
      ilusionista:     ab('Ilusão Detectada',     'Após genjutsu resistido, próximo tai +60%',          '🎭', 'battle_passive', 0.60),
      tanque:          ab('Postura de Guarda',    'Contra-ataque ao levar crítico +10% dano',           '🛡️', 'battle_passive', 0.10),
      fisico_sabio:    ab('Golpe Calculado+',     'Inteligência contribui ×0.4 no taijutsu',           '🧠', 'battle_passive', 0.40),
      artes_proibidas: ab('Lacre Mágico',         'Selo Proibido tem +15% de chance (40% total)',      '🔮', 'battle_passive', 0.40),
      feiticeiro:      ab('Domínio Expandido',    'jutsuMultiplier cap sobe para ×2.4',                '✨', 'battle_passive', 2.4),
      guardiao:        ab('Resistência Ninjutsu', 'Ninjutsu nunca causa menos de 20% dano base',       '🌊', 'battle_passive', 0.20),
      oraculo:         ab('Amplificação Elemental','elementMultiplier ×0.09 por nível',                '🔯', 'battle_passive', 0.09),
      fantasma:        ab('Sombra Letal',          'Multiplicador genjutsu ×1.8',                     '👻', 'battle_passive', 1.8),
      monge:           ab('Mente Treinada',        'Inteligência reduz dano de genjutsu +10% extra',  '🧘', 'battle_passive', 0.10),
      imortal:         ab('Corpo Eterno',           'HP máximo +10% adicional',                       '💀', 'stat_bonus', 0.10, 'hp'),
      senhor_guerra:   ab('Tática de Guerra',      'Ao derrotar oponente, recupera +5% HP extra',     '🏆', 'battle_passive', 0.05),
      protetor:        ab('Muralha Ampliada',       'HP: int×10 no cálculo do protetor',              '🏯', 'battle_passive', 10),
      ermitao:         ab('Surpresa Total',         'Primeiro ataque: crítico e ignora cap de 35%',   '🌙', 'battle_passive'),
      generico:        ab('Sabedoria do Rastreador','inteligência e selo +10 cada',                   '🐾', 'stat_bonus', 10, 'inteligencia'),
    },
  },
  {
    id: 'ninkame', name: 'Ninkame',
    description: 'A tartaruga ninja pessoal de Might Guy.',
    imageUrl: 'https://i.ibb.co/WpFNXRsM/ninkame.png',
    buffs: { taijutsu: 0, ninjutsu: 0, genjutsu: 0, selo: 0, vitalidade: 20, inteligencia: 5 },
    requiredLevel: 15, price: 2000, trainableStats: ['vitalidade', 'inteligencia'],
    buildAbilities: {
      berserker:       ab('Casco de Aço',        'Ao acertar crítico, absorve 5% do dano como HP',         '⚔️', 'turn_effect', 0.05, 'hp'),
      sombra:          ab('Adaptação Letal',     'A cada turno, +2% dano acumulado (máx 20%)',              '🌑', 'aura', 0.02),
      ilusionista:     ab('Visão 360°',          'Genjutsu não pode ser resistido no turno 1',             '🎭', 'battle_passive'),
      tanque:          ab('Carapaça Invencível', 'Redução de dano +25%',                                   '🛡️', 'battle_passive', 0.25),
      fisico_sabio:    ab('Paciência Calculada', 'Resistência mágica +35%',                               '🧠', 'battle_passive', 0.35),
      artes_proibidas: ab('Selo Ancestral',      'Encadeamento de ninjutsu após genjutsu +30% dano',       '🔮', 'battle_passive', 0.30),
      feiticeiro:      ab('Lentidão Queimante',  'Queimadura aplica 15% do dano',                         '✨', 'battle_passive', 0.15),
      guardiao:        ab('Regen Tartaruga',     'Regen +5% HP por turno',                               '🌊', 'aura', 0.05, 'hp'),
      oraculo:         ab('Escudo Arcano+',      'Redução de ninjutsu recebido +60%',                    '🔯', 'battle_passive', 0.60),
      fantasma:        ab('Carapaça Fantasma',   'Após genjutsu, ganha +10% defesa no turno',             '👻', 'turn_effect', 0.10),
      monge:           ab('Barreira Mental+',    'Redução de genjutsu recebido +50%',                    '🧘', 'battle_passive', 0.50),
      imortal:         ab('Vida Eterna',          'HP máximo +35%',                                      '💀', 'stat_bonus', 0.35, 'hp'),
      senhor_guerra:   ab('Fortitude Ancestral', 'Cada 80 pts vitalidade = +1% crítico',                  '🏆', 'battle_passive'),
      protetor:        ab('Muralha Ancestral',   'Todos os danos recebidos -20%',                         '🏯', 'aura', 0.20),
      ermitao:         ab('Sabedoria Milenar',   'Inteligência reduz dano genjutsu em 70%',               '🌙', 'battle_passive', 0.70),
      generico:        ab('Casco Protetor',       '+20 vitalidade',                                      '🐢', 'stat_bonus', 20, 'vitalidade'),
    },
  },
  {
    id: 'ninken', name: 'Ninken (8 Cães Ninjas)',
    description: 'A matilha de cães ninja de Kakashi.',
    imageUrl: 'https://i.ibb.co/mFNnx2fG/Ninken-8-Caes-Ninjas.png',
    buffs: { taijutsu: 15, ninjutsu: 0, genjutsu: 0, selo: 15, vitalidade: 10, inteligencia: 10 },
    requiredLevel: 20, price: 5000, trainableStats: ['taijutsu', 'selo', 'vitalidade', 'inteligencia'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Matilha Furiosa',    '+20% dano taijutsu, +10% chance de crítico',            '⚔️', 'battle_passive', 0.20, 'taijutsu'),
      sombra:          ab('Emboscada em Bando', 'Ataque Duplo sobe para 40% de chance',                  '🌑', 'battle_passive', 0.40),
      ilusionista:     ab('Uivo Ilusório',      'Genjutsu aplica fraqueza +30% dano recebido',           '🎭', 'battle_passive', 0.30),
      tanque:          ab('Formação Defensiva', 'Contra-ataque ao crítico devolve 40% dano',             '🛡️', 'battle_passive', 0.40),
      fisico_sabio:    ab('Caçada Inteligente', 'Inteligência entra no taijutsu com ×0.5',               '🧠', 'battle_passive', 0.50),
      artes_proibidas: ab('Garras Proibidas',   'Genjutsu sela E paralisa (25% cada)',                   '🔮', 'battle_passive', 0.25),
      feiticeiro:      ab('Aura Elemental',      'jutsuMultiplier cap sobe para ×2.5',                  '✨', 'battle_passive', 2.5),
      guardiao:        ab('Cura em Bando',       'Regen +4% HP por turno',                              '🌊', 'aura', 0.04, 'hp'),
      oraculo:         ab('Análise Elemental',   'elementMultiplier ×0.10 por nível',                   '🔯', 'battle_passive', 0.10),
      fantasma:        ab('Matilha Fantasma',    'Multiplicador genjutsu ×2.0',                         '👻', 'battle_passive', 2.0),
      monge:           ab('Harmonia da Matilha', 'Redução de todos os danos +10%',                      '🧘', 'aura', 0.10),
      imortal:         ab('8 Vidas',             'Sobreviver à morte: 8 tentativas (1× cada)',           '💀', 'battle_passive'),
      senhor_guerra:   ab('Carga em Bando',      'Ao derrotar oponente, recupera 25% HP perdido',        '🏆', 'battle_passive', 0.25),
      protetor:        ab('Formação Escudo',     'Redução de todos os danos +22%',                      '🏯', 'aura', 0.22),
      ermitao:         ab('Caçada Noturna',      'Primeiros 2 ataques da batalha são críticos',          '🌙', 'battle_passive'),
      generico:        ab('Força da Matilha',    '+15 taijutsu, +15 selo',                              '🐺', 'stat_bonus', 15, 'taijutsu'),
    },
  },
  {
    id: 'gamakichi', name: 'Gamakichi',
    description: 'O filho de Gamabunta.',
    imageUrl: 'https://i.ibb.co/rRBzXrfV/Gamakichi.png',
    buffs: { taijutsu: 10, ninjutsu: 10, genjutsu: 0, selo: 0, vitalidade: 15, inteligencia: 5 },
    requiredLevel: 25, price: 7500, trainableStats: ['taijutsu', 'ninjutsu', 'vitalidade'],
    buildAbilities: {
      berserker:       ab('Língua Cortante',   'Ao acertar crítico, próximos 2 ataques ignoram cap',    '⚔️', 'battle_passive'),
      sombra:          ab('Salto das Sombras', 'Segundo hit do Ataque Duplo = 80% dano',                '🌑', 'battle_passive', 0.80),
      ilusionista:     ab('Croáx Ilusório',    'Cooldown de genjutsu reduzido em 1 turno',             '🎭', 'battle_passive'),
      tanque:          ab('Pele Viscosa',       'Redução de dano físico +15%',                         '🛡️', 'battle_passive', 0.15),
      fisico_sabio:    ab('Salto Calculado',   '+15% dano taijutsu + int ×0.4',                       '🧠', 'battle_passive', 0.15),
      artes_proibidas: ab('Veneno de Sapo',    'Ninjutsu crítico: veneno 8% HP/turno por 2 turnos',   '🔮', 'turn_effect', 0.08, 'hp'),
      feiticeiro:      ab('Chakra do Sapo',    'Custo de ninjutsu reduzido em 10 chakra',             '✨', 'battle_passive', 10, 'chakra'),
      guardiao:        ab('Mucosa Regenerativa','Regen 4% HP/turno + absorve 3% dano como HP',        '🌊', 'aura', 0.04, 'hp'),
      oraculo:         ab('Sabedoria Batráquia','+15% elementMultiplier base',                        '🔯', 'battle_passive', 0.15),
      fantasma:        ab('Ilusão Cromática',   'Selo entra no genjutsu com ×0.5',                   '👻', 'battle_passive', 0.50),
      monge:           ab('Mente do Sapo Sábio','Inteligência entra no genjutsu com ×0.6',           '🧘', 'battle_passive', 0.60),
      imortal:         ab('Hibernação Forçada', '30% chance de sobreviver com 1 HP',                 '💀', 'battle_passive', 0.30),
      senhor_guerra:   ab('Força do Pântano',  'Cada 80 pts vitalidade = +1% crítico',               '🏆', 'battle_passive'),
      protetor:        ab('Barreira de Lama',   'Todos os danos recebidos -18%',                     '🏯', 'aura', 0.18),
      ermitao:         ab('Pulo Surpresa',       'Primeiro ataque: crítico e +30% dano',             '🌙', 'battle_passive', 0.30),
      generico:        ab('Vigor do Sapo',       '+10 taijutsu, +10 ninjutsu',                       '🐸', 'stat_bonus', 10, 'taijutsu'),
    },
  },
  {
    id: 'kyodaija', name: 'Kyodaija (Aoda)',
    description: 'Uma cobra gigante invocada por Sasuke.',
    imageUrl: 'https://i.ibb.co/fd44K2Qb/Aoda.png',
    buffs: { taijutsu: 20, ninjutsu: 0, genjutsu: 5, selo: 25, vitalidade: 0, inteligencia: 0 },
    requiredLevel: 30, price: 10000, trainableStats: ['taijutsu', 'genjutsu', 'selo'],
    buildAbilities: {
      berserker:       ab('Bote Mortal',       '+25% dano taijutsu ao atacar primeiro no turno',        '⚔️', 'battle_passive', 0.25),
      sombra:          ab('Enrolamento Sombrio','Ataque Duplo +15% chance, segundo hit = 70%',          '🌑', 'battle_passive', 0.70),
      ilusionista:     ab('Olhar Hipnótico',   'Genjutsu aplica paralisia por 1 turno (30%)',          '🎭', 'battle_passive', 0.30),
      tanque:          ab('Escamas de Titânio', 'Redução de dano físico +20%',                         '🛡️', 'battle_passive', 0.20),
      fisico_sabio:    ab('Precisão de Cobra',  'Int ×0.5 + tai no cálculo (ignora penalidade cruzada)','🧠', 'battle_passive', 0.50),
      artes_proibidas: ab('Presas Venenosas',   'Ninjutsu crítico: veneno 12% HP/turno',               '🔮', 'turn_effect', 0.12, 'hp'),
      feiticeiro:      ab('Venom Elemental',    'Queimadura de crítico causa 15% dano',                '✨', 'battle_passive', 0.15),
      guardiao:        ab('Troca de Pele',      'Abaixo de 40% HP, regenera 10% imediatamente',        '🌊', 'turn_effect', 0.10, 'hp'),
      oraculo:         ab('Veneno Arcano',      'elementMultiplier base ×0.08 por nível',              '🔯', 'battle_passive', 0.08),
      fantasma:        ab('Dança da Cobra',     'Multiplicador genjutsu ×1.9',                        '👻', 'battle_passive', 1.9),
      monge:           ab('Meditação Serpentina','Redução dano genjutsu recebido +45%',               '🧘', 'battle_passive', 0.45),
      imortal:         ab('Cobra Imortal',       'HP máximo +30%',                                   '💀', 'stat_bonus', 0.30, 'hp'),
      senhor_guerra:   ab('Esmagamento Vital',  'Cada 70 pts vitalidade = +1% crítico',               '🏆', 'battle_passive'),
      protetor:        ab('Armadura de Cobra',  'Todos os danos recebidos -20%',                      '🏯', 'aura', 0.20),
      ermitao:         ab('Ataque Relâmpago',   'Primeiro ataque: crítico e paralisa por 1 turno',    '🌙', 'battle_passive'),
      generico:        ab('Força da Serpente',  '+20 taijutsu, +25 selo',                             '🐍', 'stat_bonus', 20, 'taijutsu'),
    },
  },
  {
    id: 'enma', name: 'Rei Macaco: Enma',
    description: 'A poderosa invocação de Hiruzen Sarutobi.',
    imageUrl: 'https://i.ibb.co/m5syzZmn/Rei-Macaco-Enma.png',
    buffs: { taijutsu: 35, ninjutsu: 0, genjutsu: 0, selo: 0, vitalidade: 20, inteligencia: 15 },
    requiredLevel: 35, price: 15000, trainableStats: ['taijutsu', 'vitalidade', 'inteligencia'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Cetro de Adamante',  '+30% dano taijutsu, +12% crítico',                   '⚔️', 'battle_passive', 0.30),
      sombra:          ab('Golpe Duplo do Rei', 'Ataque Duplo: 45% chance, segundo hit = 75%',        '🌑', 'battle_passive', 0.75),
      ilusionista:     ab('Grito do Macaco Rei','Genjutsu: fraqueza +30% e paralisia (20%)',           '🎭', 'battle_passive', 0.30),
      tanque:          ab('Corpo de Adamante',  'Dano físico -25%, counter ao crítico = 40%',          '🛡️', 'battle_passive', 0.25),
      fisico_sabio:    ab('Sabedoria do Rei',   'Int ×0.6 no taijutsu, resistência mágica +35%',      '🧠', 'battle_passive', 0.60),
      artes_proibidas: ab('Selamento Real',     'Genjutsu sela E paralisa com 40% chance cada',       '🔮', 'battle_passive', 0.40),
      feiticeiro:      ab('Cetro Flamejante',   'Queimadura de crítico: 18% dano',                    '✨', 'battle_passive', 0.18),
      guardiao:        ab('Regen Real',          'Regen 5% HP + ao receber crítico recupera 3%',      '🌊', 'aura', 0.05, 'hp'),
      oraculo:         ab('Mente Régia',         'elementMultiplier ×0.10 por nível',                 '🔯', 'battle_passive', 0.10),
      fantasma:        ab('Ilusão do Rei',       'Multiplicador genjutsu ×2.0, selo ×0.5',           '👻', 'battle_passive', 2.0),
      monge:           ab('Zen Real',            'Int ×0.7 no genjutsu, redução genjutsu +55%',      '🧘', 'battle_passive', 0.55),
      imortal:         ab('Imortalidade Real',  'HP máximo +40%, sobreviver à morte: 30%',           '💀', 'battle_passive', 0.30),
      senhor_guerra:   ab('Dominância Real',    'Cada 60 pts vitalidade = +1% crítico',              '🏆', 'battle_passive'),
      protetor:        ab('Muralha Real',        'Todos os danos -25%',                              '🏯', 'aura', 0.25),
      ermitao:         ab('Rei das Sombras',     'Primeiros 2 ataques: críticos e ignoram cap',       '🌙', 'battle_passive'),
      generico:        ab('Força do Rei',         '+35 taijutsu',                                    '🐒', 'stat_bonus', 35, 'taijutsu'),
    },
  },
  {
    id: 'manda', name: 'Manda',
    description: 'A serpente mais poderosa.',
    imageUrl: 'https://i.ibb.co/S7v2N2nY/manda.png',
    buffs: { taijutsu: 30, ninjutsu: 20, genjutsu: 10, selo: 10, vitalidade: 0, inteligencia: 0 },
    requiredLevel: 40, price: 20000, trainableStats: ['taijutsu', 'ninjutsu', 'genjutsu', 'selo'],
    buildAbilities: {
      berserker:       ab('Presas Últimas',    '+35% dano taijutsu, ao crítico paralisa e ignora cap', '⚔️', 'battle_passive', 0.35),
      sombra:          ab('Ataque Supremo',    'Ataque Duplo: 50% chance, segundo hit = 80%',          '🌑', 'battle_passive', 0.80),
      ilusionista:     ab('Mente Serpentina',  'Após genjutsu falho: taijutsu +70%',                  '🎭', 'battle_passive', 0.70),
      tanque:          ab('Escamas Manda',     'Dano físico -30%, counter ao crítico = 50%',           '🛡️', 'battle_passive', 0.30),
      fisico_sabio:    ab('Predador Calculado','Int ×0.7 no taijutsu, resistência mágica +40%',       '🧠', 'battle_passive', 0.70),
      artes_proibidas: ab('Veneno Proibido',   'Veneno: 15% HP/turno por 3 turnos ao acertar genjutsu','🔮', 'turn_effect', 0.15, 'hp'),
      feiticeiro:      ab('Fogo Elemental',    'jutsuMultiplier cap ×2.6, queimadura 20%',             '✨', 'battle_passive', 2.6),
      guardiao:        ab('Pele Regenerativa', 'Regen 6% HP/turno',                                  '🌊', 'aura', 0.06, 'hp'),
      oraculo:         ab('Domínio Arcano',    'elementMultiplier ×0.12, resistência ninjutsu +60%',  '🔯', 'battle_passive', 0.12),
      fantasma:        ab('Dança da Morte',    'Multiplicador genjutsu ×2.2, paralisia 40%',          '👻', 'battle_passive', 2.2),
      monge:           ab('Mente Vazia',       'Int ×0.8 no genjutsu, redução genjutsu +60%',        '🧘', 'battle_passive', 0.60),
      imortal:         ab('Serpente Imortal',  'HP máximo +45%, sobreviver à morte: 35%',            '💀', 'battle_passive', 0.35),
      senhor_guerra:   ab('Esmagar Tudo',      'Cada 50 pts vitalidade = +1% crítico',               '🏆', 'battle_passive'),
      protetor:        ab('Armadura Manda',    'Todos os danos -28%',                                '🏯', 'aura', 0.28),
      ermitao:         ab('Ataque Primordial', 'Primeiros 3 ataques são críticos',                   '🌙', 'battle_passive'),
      generico:        ab('Força Primordial',  '+30 taijutsu, +20 ninjutsu',                         '🐍', 'stat_bonus', 30, 'taijutsu'),
    },
  },
  {
    id: 'katsuyu', name: 'Katsuyu',
    description: 'A rainha das lesmas.',
    imageUrl: 'https://i.ibb.co/zhqnH9x3/Katsuyu.png',
    buffs: { taijutsu: 0, ninjutsu: 20, genjutsu: 0, selo: 0, vitalidade: 50, inteligencia: 20 },
    requiredLevel: 45, price: 25000, trainableStats: ['ninjutsu', 'vitalidade', 'inteligencia'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Ácido Corrosivo',    'Ao acertar crítico: alvo recebe +15% dano físico no próximo turno','⚔️', 'turn_effect', 0.15),
      sombra:          ab('Divisão Tática',     '20% chance de hit dividir em 2 acertos adicionais (40%)',         '🌑', 'battle_passive', 0.40),
      ilusionista:     ab('Ilusão Corrosiva',   'Genjutsu bem-sucedido drena 5% chakra do oponente',              '🎭', 'turn_effect', 0.05, 'chakra'),
      tanque:          ab('Regen Lesma',         'Ao receber crítico, regenera 8% HP imediatamente',               '🛡️', 'turn_effect', 0.08, 'hp'),
      fisico_sabio:    ab('Ácido Calculado',    'Ninjutsu usa inteligência extra ×0.5',                           '🧠', 'battle_passive', 0.50),
      artes_proibidas: ab('Ácido Proibido',     'Após genjutsu: ninjutsu seguinte +40%',                         '🔮', 'battle_passive', 0.40),
      feiticeiro:      ab('Ácido Elemental',    'jutsuMultiplier cap ×2.8',                                       '✨', 'battle_passive', 2.8),
      guardiao:        ab('Katsuyu Cura',        'Regen 8% HP/turno, ninjutsu mínimo 25%',                       '🌊', 'aura', 0.08, 'hp'),
      oraculo:         ab('Dissolução Arcana',  'elementMultiplier ×0.13, escudo arcano +70%',                    '🔯', 'battle_passive', 0.13),
      fantasma:        ab('Ilusão Corrosiva+',  'Multiplicador genjutsu ×2.3, ácido drena 3% HP/turno',          '👻', 'aura', 0.03, 'hp'),
      monge:           ab('Mente Pura',          'Int ×0.9 no genjutsu, redução genjutsu +65%',                  '🧘', 'battle_passive', 0.65),
      imortal:         ab('Katsuyu Imortal',    'HP máximo +50%, regen passiva adicional 3%',                    '💀', 'aura', 0.03, 'hp'),
      senhor_guerra:   ab('Dissolução de Vital','Cada 40 pts vitalidade = +1% crítico',                          '🏆', 'battle_passive'),
      protetor:        ab('Escudo de Lesma',    'Todos os danos -30%, ao receber crítico absorve metade',         '🏯', 'aura', 0.30),
      ermitao:         ab('Ataque Silencioso',  'Primeiro ataque: crítico, ignora cap, drena 10% HP',             '🌙', 'battle_passive', 0.10),
      generico:        ab('Bênção da Rainha',   '+20 ninjutsu, +50 vitalidade',                                  '🐌', 'stat_bonus', 20, 'ninjutsu'),
    },
  },
  {
    id: 'gamabunta', name: 'Gamabunta',
    description: 'O Chefe dos Sapos.',
    imageUrl: 'https://i.ibb.co/s9k8SZ7v/Gamabunta.png',
    buffs: { taijutsu: 40, ninjutsu: 20, genjutsu: 0, selo: 0, vitalidade: 35, inteligencia: 10 },
    requiredLevel: 50, price: 30000, trainableStats: ['taijutsu', 'ninjutsu', 'vitalidade'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Espada do Chefe',    '+40% dano taijutsu, crítico: 2× o normal',              '⚔️', 'battle_passive', 0.40),
      sombra:          ab('Duplo do Chefe',     'Ataque Duplo: 50% chance, segundo hit = 85%',           '🌑', 'battle_passive', 0.85),
      ilusionista:     ab('Rugido Alucinante',  'Genjutsu falho: cooldown 0, uso imediato novamente',    '🎭', 'battle_passive'),
      tanque:          ab('Pele do Chefe',      'Dano físico -35%, counter ao crítico = 60%',            '🛡️', 'battle_passive', 0.35),
      fisico_sabio:    ab('Estratégia do Chefe','Int ×0.8 no taijutsu, resistência mágica +45%',        '🧠', 'battle_passive', 0.80),
      artes_proibidas: ab('Veneno do Chefe',   'Veneno 18% HP/turno por 3 turnos',                     '🔮', 'turn_effect', 0.18, 'hp'),
      feiticeiro:      ab('Chakra do Chefe',   'jutsuMultiplier cap ×3.0, custo ninjutsu -20',          '✨', 'battle_passive', 3.0),
      guardiao:        ab('Regen do Chefe',    'Regen 8% HP/turno + ninjutsu mínimo 30%',              '🌊', 'aura', 0.08, 'hp'),
      oraculo:         ab('Mente do Chefe',    'elementMultiplier ×0.15, escudo arcano +80%',           '🔯', 'battle_passive', 0.15),
      fantasma:        ab('Ilusão do Chefe',   'Multiplicador genjutsu ×2.5, paralisia 50%',            '👻', 'battle_passive', 2.5),
      monge:           ab('Calma do Chefe',    'Int ×1.0 no genjutsu, redução genjutsu +70%',          '🧘', 'battle_passive', 0.70),
      imortal:         ab('Chefe Imortal',     'HP máximo +55%, sobreviver à morte: 40%',              '💀', 'battle_passive', 0.40),
      senhor_guerra:   ab('Dominância do Chefe','Cada 40 pts vitalidade = +1% crítico',                 '🏆', 'battle_passive'),
      protetor:        ab('Muralha do Chefe',  'Todos os danos -32%',                                  '🏯', 'aura', 0.32),
      ermitao:         ab('Emboscada do Chefe','Primeiros 3 ataques: críticos e ignoram cap',           '🌙', 'battle_passive'),
      generico:        ab('Força do Chefe',    '+40 taijutsu, +20 ninjutsu',                            '🐸', 'stat_bonus', 40, 'taijutsu'),
    },
  },
  {
    id: 'baku', name: 'Baku',
    description: 'Criatura invocada por Danzō.',
    imageUrl: 'https://i.ibb.co/ZpbwCpwn/Baku.png',
    buffs: { taijutsu: 0, ninjutsu: 50, genjutsu: 0, selo: -10, vitalidade: 40, inteligencia: 0 },
    requiredLevel: 55, price: 35000, trainableStats: ['ninjutsu', 'vitalidade'],
    buildAbilities: {
      berserker:       ab('Sucção de Força',   'Ao acertar crítico, drena 8% stats de ataque do oponente', '⚔️', 'turn_effect', 0.08),
      sombra:          ab('Vácuo Sombrio',     'Ataque Duplo: cada hit drena 5% HP oponente',              '🌑', 'turn_effect', 0.05, 'hp'),
      ilusionista:     ab('Sonho Devorado',    'Genjutsu: drena 15% chakra e aplica paralisia',            '🎭', 'turn_effect', 0.15, 'chakra'),
      tanque:          ab('Absorção Vital',    'Receber dano >20% HP máx: regenera 10% de volta',          '🛡️', 'turn_effect', 0.10, 'hp'),
      fisico_sabio:    ab('Vácuo Cerebral',    'Ninjutsu usa int ×0.6, resistência mágica +40%',           '🧠', 'battle_passive', 0.60),
      artes_proibidas: ab('Selagem pelo Vácuo','Ninjutsu crítico sela chakra: oponente gasta +20 próx. turno','🔮', 'turn_effect', 20, 'chakra'),
      feiticeiro:      ab('Baku Elemental',    'jutsuMultiplier cap ×2.8',                                '✨', 'battle_passive', 2.8),
      guardiao:        ab('Sucção Vital',      'Regen 7% HP/turno + lifesteal 5% do dano ninjutsu',       '🌊', 'aura', 0.07, 'hp'),
      oraculo:         ab('Amplificação Vácuo','elementMultiplier ×0.14, escudo arcano +75%',             '🔯', 'battle_passive', 0.14),
      fantasma:        ab('Devorar Ilusões',   'Multiplicador genjutsu ×2.2, drena 10% HP ao acertar',   '👻', 'turn_effect', 0.10, 'hp'),
      monge:           ab('Mente Vazia+',      'Int ×0.9 no genjutsu, imune à paralisia',                '🧘', 'battle_passive', 0.90),
      imortal:         ab('Devorador Imortal', 'HP máximo +50%, ao sobreviver à morte drena 15% HP',     '💀', 'battle_passive', 0.15),
      senhor_guerra:   ab('Sucção Vital+',     'Cada 35 pts vitalidade = +1% crítico',                   '🏆', 'battle_passive'),
      protetor:        ab('Barreira do Vácuo', 'Todos os danos -28%, converte 5% dano em HP',            '🏯', 'aura', 0.28),
      ermitao:         ab('Vácuo Primordial',  'Primeiro ataque: crítico, drena 20% HP e chakra',         '🌙', 'battle_passive', 0.20),
      generico:        ab('Força do Vácuo',    '+50 ninjutsu, +40 vitalidade',                            '🌀', 'stat_bonus', 50, 'ninjutsu'),
    },
  },
  {
    id: 'fukasaku', name: 'Fukasaku & Shima',
    description: 'Os Dois Grandes Sábios Sapos.',
    imageUrl: 'https://i.ibb.co/LXmS2m0F/Fukasaku-Shima.png',
    buffs: { taijutsu: 10, ninjutsu: 30, genjutsu: 50, selo: 0, vitalidade: 0, inteligencia: 30 },
    requiredLevel: 60, price: 40000, trainableStats: ['ninjutsu', 'genjutsu', 'inteligencia'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Kinjutsu dos Sábios','Críticos: 50% chance de veneno + paralisia simultânea',  '⚔️', 'battle_passive', 0.50),
      sombra:          ab('Duo Sábio',          'Ataque Duplo: 55% chance, ambos os hits aplicam debuffs','🌑', 'battle_passive', 0.55),
      ilusionista:     ab('Ilusão Sábia',       'Genjutsu falho: 50% chance de refletir dano ao atacante','🎭', 'battle_passive', 0.50),
      tanque:          ab('Escudo dos Sábios',  '20% chance de anular completamente qualquer ataque',     '🛡️', 'battle_passive', 0.20),
      fisico_sabio:    ab('Sabedoria Suprema',  'Int ×1.0 no taijutsu E no genjutsu simultaneamente',    '🧠', 'battle_passive', 1.0),
      artes_proibidas: ab('Saber Proibido',     'Genjutsu sela, paralisa E envenena (25% cada)',         '🔮', 'battle_passive', 0.25),
      feiticeiro:      ab('Chakra da Natureza', 'jutsuMultiplier cap ×3.2, custo jutsu -30',             '✨', 'battle_passive', 3.2),
      guardiao:        ab('Cura dos Sábios',    'Regen 10% HP/turno, custo ninjutsu -20',                '🌊', 'aura', 0.10, 'hp'),
      oraculo:         ab('Potência Elemental', 'elementMultiplier ×0.17, escudo arcano +90%',           '🔯', 'battle_passive', 0.17),
      fantasma:        ab('Ilusão dos Sábios',  'Multiplicador genjutsu ×2.8, selo ×0.7',               '👻', 'battle_passive', 2.8),
      monge:           ab('Transcendência',     'Int ×1.2 no genjutsu, imune a genjutsu por 2 turnos',  '🧘', 'battle_passive', 1.2),
      imortal:         ab('Sábios Imortais',    'HP máximo +60%, sobreviver à morte: 50%, 2× por batalha','💀', 'battle_passive', 0.50),
      senhor_guerra:   ab('Poder dos Sábios',  'Cada 30 pts vitalidade = +1% crítico',                  '🏆', 'battle_passive'),
      protetor:        ab('Barreira dos Sábios','Todos os danos -35%',                                   '🏯', 'aura', 0.35),
      ermitao:         ab('Golpe dos Sábios',   'Primeiros 4 ataques são críticos',                     '🌙', 'battle_passive'),
      generico:        ab('Bênção dos Sábios',  '+30 ninjutsu, +50 genjutsu',                           '🐸', 'stat_bonus', 30, 'ninjutsu'),
    },
  },
  {
    id: 'shukaku', name: 'Shukaku',
    description: 'A Besta de Uma Cauda.',
    imageUrl: 'https://i.ibb.co/jvqKs6FZ/shukaku.png',
    buffs: { taijutsu: 0, ninjutsu: 60, genjutsu: 0, selo: 0, vitalidade: 50, inteligencia: 0 },
    requiredLevel: 65, price: 50000, trainableStats: ['ninjutsu', 'vitalidade'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Areia Cortante',    '+35% dano físico, areia perfura 20% da defesa',          '⚔️', 'battle_passive', 0.35),
      sombra:          ab('Tempestade de Areia','Ataque Duplo: 55% chance',                              '🌑', 'battle_passive', 0.55),
      ilusionista:     ab('Ilusão do Deserto', 'Genjutsu: drena 10% chakra do oponente por turno',      '🎭', 'aura', 0.10, 'chakra'),
      tanque:          ab('Armadura de Areia', 'Dano físico -35%, areia absorve 15% de cada ataque',    '🛡️', 'battle_passive', 0.35),
      fisico_sabio:    ab('Cálculo da Areia',  'Int ×0.7 no ninjutsu, resistência mágica +45%',        '🧠', 'battle_passive', 0.70),
      artes_proibidas: ab('Areia Proibida',    'Ninjutsu crítico: veneno de areia 15% HP/turno por 3t', '🔮', 'turn_effect', 0.15, 'hp'),
      feiticeiro:      ab('Furacão de Areia',  'jutsuMultiplier cap ×3.0',                             '✨', 'battle_passive', 3.0),
      guardiao:        ab('Escudo de Areia',   'Regen 8% HP/turno + absorve 10% de cada ataque',       '🌊', 'aura', 0.08, 'hp'),
      oraculo:         ab('Tempestade Elemental','elementMultiplier ×0.15, escudo arcano +85%',         '🔯', 'battle_passive', 0.15),
      fantasma:        ab('Miragem do Deserto', 'Multiplicador genjutsu ×2.5, paralisia 40%',           '👻', 'battle_passive', 2.5),
      monge:           ab('Mente da Areia',    'Int ×1.0 no genjutsu, redução genjutsu +70%',          '🧘', 'battle_passive', 0.70),
      imortal:         ab('Shukaku Eterno',    'HP máximo +55%, ao sobreviver: areia regenera 20%',    '💀', 'turn_effect', 0.20, 'hp'),
      senhor_guerra:   ab('Força do Deserto',  'Cada 35 pts vitalidade = +1% crítico',                 '🏆', 'battle_passive'),
      protetor:        ab('Muralha de Areia',  'Todos os danos -32%, areia reflete 8% ao atacante',    '🏯', 'aura', 0.32),
      ermitao:         ab('Areia Sombria',     'Primeiros 3 ataques: críticos',                        '🌙', 'battle_passive'),
      generico:        ab('Poder de Shukaku',  '+60 ninjutsu, +50 vitalidade',                         '🏜️', 'stat_bonus', 60, 'ninjutsu'),
    },
  },
  {
    id: 'matatabi', name: 'Matatabi',
    description: 'A Besta de Duas Caudas.',
    imageUrl: 'https://i.ibb.co/LdjHBTCT/matatabi.png',
    buffs: { taijutsu: 0, ninjutsu: 70, genjutsu: 0, selo: 20, vitalidade: 0, inteligencia: 0 },
    requiredLevel: 68, price: 55000, trainableStats: ['ninjutsu', 'selo'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Chamas Furiosas',  '+35% dano físico, ao crítico: queimadura 20% HP',           '⚔️', 'battle_passive', 0.35),
      sombra:          ab('Dança das Chamas', 'Ataque Duplo: 55% chance, segundo hit ignora 20% defesa',   '🌑', 'battle_passive', 0.55),
      ilusionista:     ab('Ilusão de Fogo',  'Genjutsu: oponente crê estar em chamas, perde 8% HP/turno', '🎭', 'aura', 0.08, 'hp'),
      tanque:          ab('Aura de Chamas',  'Aura queima quem ataca fisicamente: 5% HP devolvido',        '🛡️', 'turn_effect', 0.05, 'hp'),
      fisico_sabio:    ab('Cálculo Ígneo',   'Int ×0.8 no ninjutsu, resistência mágica +45%',             '🧠', 'battle_passive', 0.80),
      artes_proibidas: ab('Fogo Proibido',   'Ninjutsu crítico: queimadura 22% HP/turno por 3 turnos',    '🔮', 'turn_effect', 0.22, 'hp'),
      feiticeiro:      ab('Chamas Elementais','jutsuMultiplier cap ×3.0',                                 '✨', 'battle_passive', 3.0),
      guardiao:        ab('Regen das Chamas','Regen 8% HP/turno',                                        '🌊', 'aura', 0.08, 'hp'),
      oraculo:         ab('Inferno Elemental','elementMultiplier ×0.16, escudo arcano +85%',              '🔯', 'battle_passive', 0.16),
      fantasma:        ab('Fantasma de Fogo','Multiplicador genjutsu ×2.6',                              '👻', 'battle_passive', 2.6),
      monge:           ab('Serenidade das Chamas','Int ×1.0 no genjutsu, redução genjutsu +72%',         '🧘', 'battle_passive', 0.72),
      imortal:         ab('Matatabi Eterno', 'HP máximo +55%, fênix: ressurge com 25% HP (1×)',           '💀', 'turn_effect', 0.25, 'hp'),
      senhor_guerra:   ab('Inferno Vital',   'Cada 30 pts vitalidade = +1% crítico',                     '🏆', 'battle_passive'),
      protetor:        ab('Muralha de Fogo', 'Todos os danos -33%, aura reflete 10% ao atacante',         '🏯', 'aura', 0.33),
      ermitao:         ab('Chamas Sombrias', 'Primeiros 3 ataques: críticos e aplicam queimadura dupla',  '🌙', 'battle_passive'),
      generico:        ab('Poder de Matatabi','+70 ninjutsu, +20 selo',                                  '🔥', 'stat_bonus', 70, 'ninjutsu'),
    },
  },
  {
    id: 'isobu', name: 'Isobu',
    description: 'A Besta de Três Caudas.',
    imageUrl: 'https://i.ibb.co/dJHCLpbw/Isobu.png',
    buffs: { taijutsu: 0, ninjutsu: 30, genjutsu: 30, selo: 0, vitalidade: 80, inteligencia: 0 },
    requiredLevel: 71, price: 60000, trainableStats: ['ninjutsu', 'genjutsu', 'vitalidade'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Carapaça Perfurante','+35% dano físico, ignora 25% da defesa',               '⚔️', 'battle_passive', 0.35),
      sombra:          ab('Golpe das Profundezas','Ataque Duplo: 55% chance, segundo hit = 80%',        '🌑', 'battle_passive', 0.55),
      ilusionista:     ab('Névoa das Profundezas','Genjutsu: oponente com -20% precisão por 2 turnos', '🎭', 'turn_effect', 0.20),
      tanque:          ab('Carapaça Isobu',    'Dano físico -40%, ao levar crítico counter = 60%',      '🛡️', 'battle_passive', 0.40),
      fisico_sabio:    ab('Mente das Profundezas','Int ×0.8 no ninjutsu + genjutsu simultaneamente',   '🧠', 'battle_passive', 0.80),
      artes_proibidas: ab('Névoa Proibida',   'Genjutsu: sela, paralisa E aplica veneno aquático 15%', '🔮', 'turn_effect', 0.15, 'hp'),
      feiticeiro:      ab('Tsunami Elemental', 'jutsuMultiplier cap ×3.0',                             '✨', 'battle_passive', 3.0),
      guardiao:        ab('Mar Interior',      'Regen 10% HP/turno, ninjutsu mínimo 30%',              '🌊', 'aura', 0.10, 'hp'),
      oraculo:         ab('Domínio Aquático',  'elementMultiplier ×0.16, escudo arcano +90%',           '🔯', 'battle_passive', 0.16),
      fantasma:        ab('Sombra das Águas',  'Multiplicador genjutsu ×2.7, névoa drena 5% HP/turno', '👻', 'aura', 0.05, 'hp'),
      monge:           ab('Profundeza Zen',    'Int ×1.1 no genjutsu, imune à paralisia',              '🧘', 'battle_passive', 1.1),
      imortal:         ab('Isobu Eterno',      'HP máximo +65%, sobreviver à morte: 45%',              '💀', 'battle_passive', 0.45),
      senhor_guerra:   ab('Profundeza de Força','Cada 30 pts vitalidade = +1% crítico',                 '🏆', 'battle_passive'),
      protetor:        ab('Muralha de Água',   'Todos os danos -35%',                                  '🏯', 'aura', 0.35),
      ermitao:         ab('Ataque das Profundezas','Primeiros 3 ataques: críticos com debuffs em cadeia','🌙', 'battle_passive'),
      generico:        ab('Poder de Isobu',    '+30 ninjutsu, +30 genjutsu, +80 vitalidade',           '🐢', 'stat_bonus', 30, 'ninjutsu'),
    },
  },
  {
    id: 'son-goku', name: 'Son Gokū',
    description: 'A Besta de Quatro Caudas.',
    imageUrl: 'https://i.ibb.co/4w10f1YN/son-goku.png',
    buffs: { taijutsu: 70, ninjutsu: 40, genjutsu: 0, selo: 0, vitalidade: 30, inteligencia: 0 },
    requiredLevel: 74, price: 65000, trainableStats: ['taijutsu', 'ninjutsu', 'vitalidade'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Fúria do Rei Macaco','+45% dano físico, crítico: 2 ataques grátis (30%)',    '⚔️', 'battle_passive', 0.45),
      sombra:          ab('Macaco Sombrio',     'Ataque Duplo: 60% chance, segundo hit = 90%',          '🌑', 'battle_passive', 0.90),
      ilusionista:     ab('Rugido Alucinante+', 'Genjutsu falho: reflete 30% do dano ao atacante',     '🎭', 'battle_passive', 0.30),
      tanque:          ab('Pelo de Ferro',      'Dano físico -40%, counter ao crítico = 70%',           '🛡️', 'battle_passive', 0.40),
      fisico_sabio:    ab('Macaco Sábio',       'Int ×0.9 no taijutsu, resistência mágica +50%',       '🧠', 'battle_passive', 0.90),
      artes_proibidas: ab('Lava Proibida',      'Ninjutsu crítico: queimadura de lava 25% HP/turno 3t','🔮', 'turn_effect', 0.25, 'hp'),
      feiticeiro:      ab('Erupção Elemental',  'jutsuMultiplier cap ×3.2',                            '✨', 'battle_passive', 3.2),
      guardiao:        ab('Força Regenerativa', 'Regen 9% HP/turno, lifesteal 8% dano taijutsu',       '🌊', 'aura', 0.09, 'hp'),
      oraculo:         ab('Mente Ardente',      'elementMultiplier ×0.18, escudo arcano +90%',          '🔯', 'battle_passive', 0.18),
      fantasma:        ab('Sombra de Lava',     'Multiplicador genjutsu ×2.8, lava paralisa e queima', '👻', 'battle_passive', 2.8),
      monge:           ab('Zen do Macaco',      'Int ×1.2 no genjutsu, redução genjutsu +75%',         '🧘', 'battle_passive', 0.75),
      imortal:         ab('Son Eterno',          'HP máximo +60%, sobreviver à morte: 50%',            '💀', 'battle_passive', 0.50),
      senhor_guerra:   ab('Rei dos Guerreiros', 'Cada 25 pts vitalidade = +1% crítico',                '🏆', 'battle_passive'),
      protetor:        ab('Muralha de Lava',    'Todos os danos -36%, aura queima atacantes 8%',       '🏯', 'aura', 0.36),
      ermitao:         ab('Emboscada do Rei',   'Primeiros 4 ataques: críticos com queimadura dupla',  '🌙', 'battle_passive'),
      generico:        ab('Poder de Son Gokū',  '+70 taijutsu, +40 ninjutsu',                          '🐵', 'stat_bonus', 70, 'taijutsu'),
    },
  },
  {
    id: 'kokuo', name: 'Kokuō',
    description: 'A Besta de Cinco Caudas.',
    imageUrl: 'https://i.ibb.co/fdm6tJ2h/Kokuo.png',
    buffs: { taijutsu: 0, ninjutsu: 80, genjutsu: 0, selo: 20, vitalidade: 0, inteligencia: 10 },
    requiredLevel: 77, price: 70000, trainableStats: ['ninjutsu', 'selo', 'inteligencia'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Chifres Celestiais','+40% dano físico, perfura 30% defesa',                  '⚔️', 'battle_passive', 0.40),
      sombra:          ab('Unicórnio Sombrio', 'Ataque Duplo: 60% chance, segundo hit = 90%',           '🌑', 'battle_passive', 0.90),
      ilusionista:     ab('Véu Celestial',     'Genjutsu: paralisia 45% + cega oponente (-20% acertos)','🎭', 'battle_passive', 0.45),
      tanque:          ab('Armadura Celestial', 'Dano físico -40%, counter ao crítico = 70%',           '🛡️', 'battle_passive', 0.40),
      fisico_sabio:    ab('Sapiência dos Cinco','Int ×1.0 no ninjutsu, resistência mágica +55%',       '🧠', 'battle_passive', 1.0),
      artes_proibidas: ab('Selagem Celestial', 'Genjutsu: sela, paralisa, envenena E cega (25% cada)', '🔮', 'battle_passive', 0.25),
      feiticeiro:      ab('Chakra Celestial',  'jutsuMultiplier cap ×3.3, custo jutsu -35',            '✨', 'battle_passive', 3.3),
      guardiao:        ab('Cura Celestial',    'Regen 10% HP/turno',                                   '🌊', 'aura', 0.10, 'hp'),
      oraculo:         ab('Amplificação Celestial','elementMultiplier ×0.19, escudo arcano +95%',      '🔯', 'battle_passive', 0.19),
      fantasma:        ab('Fantasma Celestial','Multiplicador genjutsu ×3.0',                          '👻', 'battle_passive', 3.0),
      monge:           ab('Mente Divina',      'Int ×1.3 no genjutsu, imune à paralisia e silêncio',   '🧘', 'battle_passive', 1.3),
      imortal:         ab('Kokuō Eterno',      'HP máximo +65%, sobreviver à morte: 55%, 2× por batalha','💀', 'battle_passive', 0.55),
      senhor_guerra:   ab('Cinco Forças',      'Cada 20 pts vitalidade = +1% crítico',                 '🏆', 'battle_passive'),
      protetor:        ab('Cinco Escudos',     'Todos os danos -38%',                                  '🏯', 'aura', 0.38),
      ermitao:         ab('Transcendência Celestial','Primeiros 4 ataques: críticos e ignoram cap',    '🌙', 'battle_passive'),
      generico:        ab('Poder de Kokuō',   '+80 ninjutsu, +20 selo',                                '🦄', 'stat_bonus', 80, 'ninjutsu'),
    },
  },
  {
    id: 'saiken', name: 'Saiken',
    description: 'A Besta de Seis Caudas.',
    imageUrl: 'https://i.ibb.co/3mwyyrS2/saiken.png',
    buffs: { taijutsu: 0, ninjutsu: 60, genjutsu: 0, selo: 0, vitalidade: 60, inteligencia: 0 },
    requiredLevel: 80, price: 75000, trainableStats: ['ninjutsu', 'vitalidade'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Gosma Cortante',   '+40% dano físico, ao crítico: alvo lento (-10% dano 2 turnos)','⚔️', 'battle_passive', 0.40),
      sombra:          ab('Veneno nas Sombras','Ataque Duplo: 60% chance, ambos os hits envenenam',           '🌑', 'battle_passive', 0.60),
      ilusionista:     ab('Ilusão Corrosiva++','Genjutsu: drena 12% HP/turno por 3 turnos',                  '🎭', 'aura', 0.12, 'hp'),
      tanque:          ab('Gosma Defensiva',  'Dano físico -42%, gosma reflete 8% ao atacante',              '🛡️', 'battle_passive', 0.42),
      fisico_sabio:    ab('Cálculo da Gosma', 'Int ×0.9 no ninjutsu, resistência mágica +55%',               '🧠', 'battle_passive', 0.90),
      artes_proibidas: ab('Gosma Proibida',   'Ninjutsu crítico: veneno ácido 20% HP/turno por 4 turnos',    '🔮', 'turn_effect', 0.20, 'hp'),
      feiticeiro:      ab('Ácido Elemental+', 'jutsuMultiplier cap ×3.3',                                    '✨', 'battle_passive', 3.3),
      guardiao:        ab('Regen Ácida',       'Regen 10% HP/turno, lifesteal 10% dano ninjutsu',            '🌊', 'aura', 0.10, 'hp'),
      oraculo:         ab('Amplificação Corrosiva','elementMultiplier ×0.19, escudo arcano +95%',            '🔯', 'battle_passive', 0.19),
      fantasma:        ab('Fantasma da Gosma','Multiplicador genjutsu ×2.9',                                 '👻', 'battle_passive', 2.9),
      monge:           ab('Serenidade Ácida', 'Int ×1.2 no genjutsu, imune a veneno',                       '🧘', 'battle_passive', 1.2),
      imortal:         ab('Saiken Eterno',    'HP máximo +68%, ao sobreviver: gosma absorve 30% próx. ataque','💀', 'battle_passive', 0.30),
      senhor_guerra:   ab('Força Corrosiva',  'Cada 20 pts vitalidade = +1% crítico',                       '🏆', 'battle_passive'),
      protetor:        ab('Muralha Ácida',    'Todos os danos -40%, ácido consome 10% HP atacante',          '🏯', 'aura', 0.40),
      ermitao:         ab('Ataque Corrosivo', 'Primeiros 4 ataques: críticos + veneno duplo em cadeia',      '🌙', 'battle_passive'),
      generico:        ab('Poder de Saiken',  '+60 ninjutsu, +60 vitalidade',                                '🐛', 'stat_bonus', 60, 'ninjutsu'),
    },
  },
  {
    id: 'chomei', name: 'Chōmei',
    description: 'A Besta de Sete Caudas.',
    imageUrl: 'https://i.ibb.co/HfK49xKt/Chomei.png',
    buffs: { taijutsu: 20, ninjutsu: 0, genjutsu: 40, selo: 50, vitalidade: 0, inteligencia: 0 },
    requiredLevel: 83, price: 80000, trainableStats: ['taijutsu', 'genjutsu', 'selo'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Asas de Aço',      '+42% dano físico, sempre ataca primeiro no turno',       '⚔️', 'battle_passive', 0.42),
      sombra:          ab('Dupla Asa',        'Ataque Duplo: 65% chance, segundo hit = 90% + paralisia','🌑', 'battle_passive', 0.65),
      ilusionista:     ab('Ilusão das 7 Asas','Genjutsu: drena 10% chakra E 5% HP por turno',          '🎭', 'aura'),
      tanque:          ab('Casco de Besouro', 'Dano físico -45%, asas desviam: 15% chance de miss',     '🛡️', 'battle_passive', 0.45),
      fisico_sabio:    ab('7 Estratégias',    'Int ×1.0 no taijutsu, resistência mágica +55%',         '🧠', 'battle_passive', 1.0),
      artes_proibidas: ab('Pó das 7 Caudas', 'Genjutsu: sela, paralisa, envenena, cega E drena chakra (20% cada)','🔮', 'battle_passive', 0.20),
      feiticeiro:      ab('Chakra das 7 Caudas','jutsuMultiplier cap ×3.5, custo jutsu -40',           '✨', 'battle_passive', 3.5),
      guardiao:        ab('Cura das 7 Asas', 'Regen 10% HP/turno + ao usar defend regen vira 20%',     '🌊', 'aura', 0.10, 'hp'),
      oraculo:         ab('7 Elementos',      'elementMultiplier ×0.20, escudo arcano +100%',           '🔯', 'battle_passive', 0.20),
      fantasma:        ab('Sete Fantasmas',   'Multiplicador genjutsu ×3.2',                           '👻', 'battle_passive', 3.2),
      monge:           ab('7 Meditações',     'Int ×1.4 no genjutsu, imune à paralisia, veneno e silêncio','🧘', 'battle_passive', 1.4),
      imortal:         ab('Chōmei Eterno',    'HP máximo +70%, sobreviver à morte: 60%, 2× por batalha','💀', 'battle_passive', 0.60),
      senhor_guerra:   ab('7 Vitórias',       'Cada 20 pts vitalidade = +1.5% crítico',               '🏆', 'battle_passive'),
      protetor:        ab('7 Escudos',        'Todos os danos -42%',                                   '🏯', 'aura', 0.42),
      ermitao:         ab('Golpe das 7 Asas', 'Primeiros 5 ataques: críticos, último ignora TODA defesa','🌙', 'battle_passive'),
      generico:        ab('Poder de Chōmei',  '+20 taijutsu, +40 genjutsu, +50 selo',                  '🦋', 'stat_bonus', 20, 'taijutsu'),
    },
  },
  {
    id: 'gyuki', name: 'Gyūki',
    description: 'A Besta de Oito Caudas.',
    imageUrl: 'https://i.ibb.co/d4gKMD18/Gyuki.png',
    buffs: { taijutsu: 80, ninjutsu: 50, genjutsu: 0, selo: 0, vitalidade: 40, inteligencia: 0 },
    requiredLevel: 86, price: 85000, trainableStats: ['taijutsu', 'ninjutsu', 'vitalidade'],
    buildAbilities: {
      berserker:       ab('Tentáculos de Aço','+50% dano físico, ao crítico: 2 tentáculos extras (20%)', '⚔️', 'battle_passive', 0.50),
      sombra:          ab('8 Golpes Sombrios','Ataque Duplo: 70% chance, segundo hit = 95%',            '🌑', 'battle_passive', 0.70),
      ilusionista:     ab('Kraken Ilusório',  'Genjutsu: 8 tentáculos causam 5% HP cada',              '🎭', 'turn_effect', 0.05, 'hp'),
      tanque:          ab('Carapaça do Kraken','Dano físico -48%, ao levar crítico: 8 counter attacks', '🛡️', 'battle_passive', 0.48),
      fisico_sabio:    ab('8 Estratégias',    'Int ×1.1 no taijutsu + ninjutsu simultaneamente',       '🧠', 'battle_passive', 1.1),
      artes_proibidas: ab('Tinta Proibida',   'Genjutsu: tinta paralisa, sela E aplica 8 venenos',     '🔮', 'battle_passive'),
      feiticeiro:      ab('Chakra dos 8',     'jutsuMultiplier cap ×3.6, custo jutsu -40, queimadura 25%','✨', 'battle_passive', 3.6),
      guardiao:        ab('Regen do Kraken',  'Regen 12% HP/turno, lifesteal 12% do dano físico',      '🌊', 'aura', 0.12, 'hp'),
      oraculo:         ab('8 Elementos',      'elementMultiplier ×0.22, anula 1 ataque/batalha',       '🔯', 'battle_passive', 0.22),
      fantasma:        ab('8 Fantasmas',      'Multiplicador genjutsu ×3.4, paralisia 60%, cega 40%',  '👻', 'battle_passive', 3.4),
      monge:           ab('8 Meditações',     'Int ×1.5 no genjutsu, imune a todos os debuffs',        '🧘', 'battle_passive', 1.5),
      imortal:         ab('Gyūki Eterno',     'HP máximo +75%, sobreviver à morte: 65%, 3× por batalha','💀', 'battle_passive', 0.65),
      senhor_guerra:   ab('8 Vitórias',       'Cada 15 pts vitalidade = +1% crítico',                  '🏆', 'battle_passive'),
      protetor:        ab('8 Escudos',        'Todos os danos -45%, cada 2 recebidos anula o próximo', '🏯', 'aura', 0.45),
      ermitao:         ab('Golpe dos 8',      'Primeiros 5 ataques: críticos, todos ignoram cap E defesa','🌙', 'battle_passive'),
      generico:        ab('Poder de Gyūki',   '+80 taijutsu, +50 ninjutsu',                             '🐙', 'stat_bonus', 80, 'taijutsu'),
    },
  },
  {
    id: 'kurama', name: 'Kurama',
    description: 'A Besta de Nove Caudas.',
    imageUrl: 'https://i.ibb.co/pBCPJnjg/kurama.png',
    buffs: { taijutsu: 0, ninjutsu: 100, genjutsu: 0, selo: 0, vitalidade: 100, inteligencia: 0 },
    requiredLevel: 90, price: 90000, trainableStats: ['ninjutsu', 'vitalidade'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Rajada das 9 Caudas','+60% dano físico, crítico: 9 explosões (8% HP cada)',  '⚔️', 'battle_passive', 0.60),
      sombra:          ab('9 Sombras',          'Ataque Duplo: 75% chance, segundo hit = 100%',          '🌑', 'battle_passive', 0.75),
      ilusionista:     ab('Ilusão de Kurama',   'Genjutsu: oponente perde turno (40% chance)',           '🎭', 'battle_passive', 0.40),
      tanque:          ab('Pele de Kurama',     'Dano físico -55%, counter ao crítico = 80%',            '🛡️', 'battle_passive', 0.55),
      fisico_sabio:    ab('Sabedoria das 9',    'Int ×1.3 no ninjutsu + taijutsu simultaneamente',       '🧠', 'battle_passive', 1.3),
      artes_proibidas: ab('Selagem de Kurama',  'Genjutsu sela TUDO por 1 turno (35%)',                  '🔮', 'battle_passive', 0.35),
      feiticeiro:      ab('Chakra das 9',       'jutsuMultiplier cap ×4.0, custo jutsu -50',             '✨', 'battle_passive', 4.0),
      guardiao:        ab('Regen das 9 Caudas', 'Regen 15% HP/turno, lifesteal 15% de todo dano',        '🌊', 'aura', 0.15, 'hp'),
      oraculo:         ab('9 Elementos',        'elementMultiplier ×0.25, anula 2 ataques/batalha',      '🔯', 'battle_passive', 0.25),
      fantasma:        ab('9 Fantasmas',        'Multiplicador genjutsu ×4.0',                          '👻', 'battle_passive', 4.0),
      monge:           ab('9 Meditações',       'Int ×2.0 no genjutsu, imune a TODOS os debuffs',       '🧘', 'battle_passive', 0.90),
      imortal:         ab('Kurama Imortal',     'HP máximo +100%, sobreviver à morte: 80%, ilimitado',  '💀', 'battle_passive', 0.80),
      senhor_guerra:   ab('9 Guerreiros',       'Cada 10 pts vitalidade = +1% crítico',                 '🏆', 'battle_passive'),
      protetor:        ab('9 Escudos',          'Todos os danos -55%, anula 3 ataques/batalha',         '🏯', 'aura', 0.55),
      ermitao:         ab('Golpe das 9 Caudas', 'Primeiros 6 ataques: críticos, ignoram cap, defesa E imunidades','🌙', 'battle_passive'),
      generico:        ab('Poder de Kurama',    '+100 ninjutsu, +100 vitalidade',                       '🦊', 'stat_bonus', 100, 'ninjutsu'),
    },
  },
  {
    id: 'juubi', name: 'Jūbi',
    description: 'A Besta de Dez Caudas.',
    imageUrl: 'https://i.ibb.co/NgjX895C/Jubi.png',
    buffs: { taijutsu: 100, ninjutsu: 100, genjutsu: 100, selo: 100, vitalidade: 100, inteligencia: 100 },
    requiredLevel: 100, price: 1000000,
    trainableStats: ['taijutsu', 'ninjutsu', 'genjutsu', 'selo', 'vitalidade', 'inteligencia'], isPremium: true,
    buildAbilities: {
      berserker:       ab('Destruição Total',      '+70% dano físico, cada crítico encadeia 3 ataques (50%)',      '⚔️', 'battle_passive', 0.70),
      sombra:          ab('10 Sombras Absolutas',  'Ataque Duplo: 80% chance, segundo hit = 120% dano',           '🌑', 'battle_passive', 0.80),
      ilusionista:     ab('Ilusão de Tsukuyomi',   'Genjutsu: paralisa 2 turnos (50% chance)',                    '🎭', 'battle_passive', 0.50),
      tanque:          ab('Corpo do Criador',       'Dano físico -65%, counter ao crítico = 100%',                '🛡️', 'battle_passive', 0.65),
      fisico_sabio:    ab('Onisciência',            'Int ×2.0 em TODOS os stats de ataque',                       '🧠', 'battle_passive', 2.0),
      artes_proibidas: ab('Selagem do Criador',     'Genjutsu sela ABSOLUTAMENTE TUDO por 2 turnos (50%)',        '🔮', 'battle_passive', 0.50),
      feiticeiro:      ab('Chakra Primordial',      'jutsuMultiplier cap ×5.0, custo jutsu 0',                    '✨', 'battle_passive', 5.0),
      guardiao:        ab('Regen do Criador',       'Regen 20% HP/turno, lifesteal 20%, chakra se regenera',      '🌊', 'aura', 0.20, 'hp'),
      oraculo:         ab('10 Elementos',           'elementMultiplier ×0.35, anula todos ataques no turno 1',    '🔯', 'battle_passive', 0.35),
      fantasma:        ab('10 Fantasmas Eternos',   'Multiplicador genjutsu ×6.0, TODOS debuffs (60%)',           '👻', 'battle_passive', 6.0),
      monge:           ab('Transcendência Total',   'Int ×3.0 no genjutsu, imune a TODO debuff, redução gen +100%','🧘', 'battle_passive', 3.0),
      imortal:         ab('Jūbi Eterno',            'HP máximo +200%, sobreviver à morte SEMPRE, 5 vezes',        '💀', 'battle_passive'),
      senhor_guerra:   ab('10 Guerreiros Supremos', 'Cada ponto de vitalidade = +0.1% crítico',                   '🏆', 'battle_passive'),
      protetor:        ab('10 Escudos Absolutos',   'Todos os danos -70%, anula TODOS ataques no turno 1',       '🏯', 'aura', 0.70),
      ermitao:         ab('Golpe Primordial',        'TODOS os ataques são críticos e ignoram tudo',              '🌙', 'battle_passive'),
      generico:        ab('Poder Absoluto',          '+100 em TODOS os stats',                                    '⭐', 'stat_bonus', 100, 'taijutsu'),
    },
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FUNÇÕES AUXILIARES
// ─────────────────────────────────────────────────────────────────────────────

export function getSummonBuildAbility(summonId: string, build: BuildType): SummonBuildAbility | null {
  const summon = summonsData.find(s => s.id === summonId);
  if (!summon) return null;
  return summon.buildAbilities[build] ?? summon.buildAbilities['generico'] ?? null;
}

export function getSummonById(id: string): Summon | undefined {
  return summonsData.find(s => s.id === id);
}

export const getTrainingCost = (currentLevel: number): number => {
  if (currentLevel >= MAX_SUMMON_LEVEL) return 0;
  const BASE_TRAINING_COST = 10000;
  const COST_MULTIPLIER = 1.5;
  return Math.floor(BASE_TRAINING_COST * Math.pow(COST_MULTIPLIER, currentLevel - 1));
};

export const MAX_SUMMON_LEVEL = 10;
export const TRAINING_BONUS_PER_LEVEL = 5;