export type Weapon = {
    id: string;
    name: string;
    description: string;
    imageUrl: string;
    type: 'Lâmina Curta' | 'Espada Grande' | 'Ferramenta Ninja' | 'Marionete' | 'Lendária';
    buffs: {
        taijutsu: number;
        ninjutsu: number;
        genjutsu: number;
        selo: number;
        vitalidade: number;
        inteligencia: number;
    };
    requiredLevel: number;
    price: number;
    isPremium?: boolean;
};

// Organizado por poder crescente
export const weaponsData: Weapon[] = [
    // Nível Genin
    {
        id: 'senbon',
        name: 'Senbon',
        description: 'Agulhas metálicas longas e finas usadas para ataques rápidos e precisos, visando pontos de pressão. Requer grande precisão.',
        imageUrl: 'https://i.ibb.co/9kxbsnpz/senbol.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: -2, ninjutsu: 0, genjutsu: 0, selo: 8, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 1,
        price: 200,
    },
    {
        id: 'kunai',
        name: 'Kunai Simples',
        description: 'Uma ferramenta ninja versátil, usada tanto para combate corpo a corpo quanto como projétil. Essencial para qualquer shinobi.',
        imageUrl: 'https://i.ibb.co/h1LTrHxs/kunai-simples.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: 5, ninjutsu: 0, genjutsu: -1, selo: 0, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 1,
        price: 250,
    },
    {
        id: 'shuriken',
        name: 'Shuriken Simples',
        description: 'Uma estrela de arremesso afiada. Perfeita para distrair inimigos ou para ataques rápidos à distância.',
        imageUrl: 'https://i.ibb.co/yFXxHVkH/Shuriken-Simples.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: 0, ninjutsu: 0, genjutsu: 0, selo: 5, vitalidade: -1, inteligencia: 0 },
        requiredLevel: 1,
        price: 250,
    },
     {
        id: 'kunai_explosiva',
        name: 'Kunai Explosiva',
        description: 'Uma kunai com um selo explosivo anexado. Causa dano em área ao impactar.',
        imageUrl: 'https://i.ibb.co/6cZjJ7SY/Kunai-Explosiva.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: 2, ninjutsu: 8, genjutsu: 0, selo: -2, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 4,
        price: 700,
    },
    {
        id: 'fuma_shuriken',
        name: 'Fūma Shuriken',
        description: 'Uma shuriken gigante e dobrável com quatro lâminas. Causa mais dano que uma shuriken comum, mas é mais lenta.',
        imageUrl: 'https://i.ibb.co/fYLd8dr3/Fuma-Shuriken.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: 12, ninjutsu: 0, genjutsu: 0, selo: -3, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 5,
        price: 800,
    },
    {
        id: 'tanto',
        name: 'Tantō',
        description: 'Uma adaga curta e ágil, ideal para combates rápidos e ataques furtivos. Favorece a velocidade e a precisão.',
        imageUrl: 'https://i.ibb.co/7NgPzhQq/Tanto.png',
        type: 'Lâmina Curta',
        buffs: { taijutsu: 10, ninjutsu: 0, genjutsu: -2, selo: 10, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 8,
        price: 1200,
    },
    // Nível Chunin
    {
        id: 'katana',
        name: 'Katana Padrão',
        description: 'Uma espada longa e curva, a arma preferida de muitos samurais e ninjas espadachins. Oferece um bom equilíbrio entre ataque e defesa.',
        imageUrl: 'https://i.ibb.co/SD0f5vMz/Katana-Padrao.png',
        type: 'Lâmina Curta',
        buffs: { taijutsu: 15, ninjutsu: 0, genjutsu: 0, selo: -2, vitalidade: 5, inteligencia: 0 },
        requiredLevel: 10,
        price: 1500,
    },
    {
        id: 'karasu',
        name: 'Marionete: Karasu',
        description: 'Uma marionete de ataque criada por Kankurō, cheia de lâminas venenosas e mecanismos ocultos.',
        imageUrl: 'https://i.ibb.co/j9xZZZfN/Karasu.png',
        isPremium: true,
        type: 'Marionete',
        buffs: { taijutsu: -10, ninjutsu: 20, genjutsu: 0, selo: 15, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 12,
        price: 2500,
    },
    {
        id: 'leque_gigante',
        name: 'Leque Gigante',
        description: 'A arma icônica de Temari. Pode gerar rajadas de vento poderosas, amplificando jutsus Futon e repelindo inimigos.',
        imageUrl: 'https://i.ibb.co/8DVBTCYd/Leque-Gigante.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: -5, ninjutsu: 25, genjutsu: 0, selo: 0, vitalidade: 0, inteligencia: 5 },
        requiredLevel: 15,
        price: 3000,
    },
    {
        id: 'aian_nakkuru',
        name: 'Lâminas de Vento (Asuma)',
        description: 'Facas de trincheira especiais que podem ser infundidas com chakra do vento para aumentar drasticamente seu poder de corte.',
        imageUrl: 'https://i.ibb.co/r2t3XFDj/Laminas-de-Vento.png',
        type: 'Lâmina Curta',
        buffs: { taijutsu: 15, ninjutsu: 15, genjutsu: 0, selo: 5, vitalidade: -5, inteligencia: 0 },
        requiredLevel: 20,
        price: 7500,
    },
    // Nível Jounin
    {
        id: 'kubikiribocho',
        name: 'Kubikiribōchō',
        description: 'A "Lâmina do Carrasco" de Zabuza. Uma espada gigante que se regenera usando o ferro do sangue de suas vítimas.',
        imageUrl: 'https://i.ibb.co/fYpRbCMP/kubikiribocho.png',
        type: 'Espada Grande',
        buffs: { taijutsu: 40, ninjutsu: 0, genjutsu: 0, selo: -10, vitalidade: 15, inteligencia: 0 },
        requiredLevel: 25,
        price: 12000,
    },
    {
        id: 'cabaca_gaara',
        name: 'Cabaça de Areia',
        description: 'A cabaça de Gaara, infundida com chakra, que carrega areia especial para ataques e defesas rápidas. Aumenta o poder do Ninjutsu e a Inteligência.',
        imageUrl: 'https://i.ibb.co/bgsBPnqf/Cabaca-de-Areia.png',
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: -10, ninjutsu: 35, genjutsu: 0, selo: 0, vitalidade: 5, inteligencia: 15 },
        requiredLevel: 28,
        price: 13500,
    },
    {
        id: 'samehada',
        name: 'Samehada',
        description: 'A "Pele de Tubarão" de Kisame. Uma espada viva que se alimenta de chakra. Ela rasga em vez de cortar e só se une a quem tem grandes reservas de energia.',
        imageUrl: 'https://i.ibb.co/Y4xkw5Rk/samehada.png',
        isPremium: true,
        type: 'Espada Grande',
        buffs: { taijutsu: 15, ninjutsu: 35, genjutsu: 0, selo: -10, vitalidade: 30, inteligencia: 0 },
        requiredLevel: 30,
        price: 15000,
    },
    {
        id: 'hiramekarei',
        name: 'Hiramekarei',
        description: 'Uma espada de dois cabos que pode armazenar e liberar chakra, moldando-o em diferentes formas, como um martelo ou uma longa espada.',
        imageUrl: 'https://i.ibb.co/8gTccCkp/Hiramekarei.png',
        type: 'Espada Grande',
        buffs: { taijutsu: 10, ninjutsu: 40, genjutsu: 0, selo: -5, vitalidade: 0, inteligencia: 15 },
        requiredLevel: 32,
        price: 18000,
    },
    {
        id: 'marionete_sasori',
        name: 'Marionete: Hiruko',
        description: 'A marionete defensiva favorita de Sasori, com uma cauda de escorpião venenosa e um casco quase impenetrável.',
        imageUrl: 'https://i.ibb.co/7NJxRncL/Marionete-Hiruko.png',
        type: 'Marionete',
        buffs: { taijutsu: -20, ninjutsu: 40, genjutsu: 10, selo: 0, vitalidade: 25, inteligencia: 0 },
        requiredLevel: 34,
        price: 21000,
    },
    {
        id: 'kiba',
        name: 'Kiba',
        description: 'Espadas gêmeas infundidas com o elemento raio, capazes de gerar e controlar relâmpagos. Aumentam a velocidade e o poder dos jutsus Raiton.',
        imageUrl: 'https://i.ibb.co/wFjkwGdK/kiba-1.png',
        type: 'Lâmina Curta',
        buffs: { taijutsu: 10, ninjutsu: 30, genjutsu: 0, selo: 25, vitalidade: 0, inteligencia: -5 },
        requiredLevel: 35,
        price: 22000,
    },
    {
        id: 'kusanagi',
        name: 'Espada Kusanagi',
        description: 'A lendária espada de Orochimaru, capaz de se estender a grandes distâncias e ser controlada remotamente.',
        imageUrl: 'https://i.ibb.co/prn0MbYS/Espada-Kusanagi-1.png',
        type: 'Lendária',
        buffs: { taijutsu: 25, ninjutsu: 15, genjutsu: 0, selo: 25, vitalidade: 0, inteligencia: 20 },
        requiredLevel: 40,
        price: 25000,
    },
    {
        id: 'foice_tripla',
        name: 'Foice de Lâmina Tripla',
        description: 'A arma profana de Hidan. Uma foice gigante com três lâminas, projetada para coletar sangue para seus rituais de maldição.',
        imageUrl: 'https://i.ibb.co/XxNS6x7p/Foice-de-Lamina-Tripla.png',
        type: 'Lendária',
        buffs: { taijutsu: 30, ninjutsu: -10, genjutsu: 0, selo: 0, vitalidade: 40, inteligencia: -10 },
        requiredLevel: 42,
        price: 27000,
    },
    // Nível Kage
    {
        id: 'shibuki',
        name: 'Shibuki',
        description: 'A "Espada de Explosão", que combina esgrima com explosões. Contém um pergaminho cheio de selos explosivos.',
        imageUrl: 'https://i.ibb.co/RphnpLdt/shibuki.png',
        type: 'Espada Grande',
        buffs: { taijutsu: 20, ninjutsu: 45, genjutsu: 0, selo: 0, vitalidade: -10, inteligencia: 0 },
        requiredLevel: 45,
        price: 28000,
    },
    {
        id: 'nuibari',
        name: 'Nuibari',
        description: 'A "Agulha de Costura", uma espada longa e fina que pode perfurar vários inimigos e costurá-los com um fio de aço.',
        imageUrl: 'https://i.ibb.co/hxLm7PTC/Nuibari.png',
        type: 'Lendária',
        buffs: { taijutsu: -5, ninjutsu: 20, genjutsu: 25, selo: 40, vitalidade: 0, inteligencia: 0 },
        requiredLevel: 52,
        price: 32000,
    },
    {
        id: 'kabutowari',
        name: 'Kabutowari',
        description: 'O "Rachador de Elmos". Uma combinação de um machado e um martelo que dizem ser capaz de quebrar qualquer defesa.',
        imageUrl: 'https://i.ibb.co/C3ZMzDZh/Kabutowari.png',
        type: 'Espada Grande',
        buffs: { taijutsu: 60, ninjutsu: 0, genjutsu: 0, selo: -30, vitalidade: 20, inteligencia: 0 },
        requiredLevel: 55,
        price: 35000,
    },
    {
        id: 'gunbai',
        name: 'Gunbai (Leque Uchiha)',
        description: 'O leque de guerra de Madara Uchiha. Pode refletir ataques, converter chakra em vento e ser usado como uma maça ou escudo.',
        imageUrl: 'https://i.ibb.co/7Jbqrdmc/Gunbai-Leque-Uchiha.png',
        type: 'Lendária',
        buffs: { taijutsu: 10, ninjutsu: 20, genjutsu: 40, selo: 0, vitalidade: -10, inteligencia: 30 },
        requiredLevel: 58,
        price: 45000,
    },
    // Nível Lendário / Divino
    {
        id: 'samehada_v2',
        name: 'Samehada (Forma Liberada)',
        description: 'A verdadeira forma da Samehada quando totalmente desperta. A espada viva revela sua natureza de criatura, com escamas afiadas e capacidade massiva de devorar chakra. Apenas shinobis com reservas de chakra colossais podem empunhá-la neste estado.',
        imageUrl: 'https://i.ibb.co/0prcPQbW/samehada2.png',
        isPremium: true,
        type: 'Espada Grande',
        buffs: { taijutsu: 25, ninjutsu: 55, genjutsu: 0, selo: -15, vitalidade: 50, inteligencia: 10 },
        requiredLevel: 60,
        price: 50000,
    },
    {
        id: 'bashosen',
        name: 'Bashōsen',
        description: 'O Leque de Plumas de Bananeira, uma das Ferramentas Valiosas do Sábio dos Seis Caminhos. Pode gerar qualquer um dos cinco elementos.',
        imageUrl: 'https://i.ibb.co/Kz72PVBw/Bashosen.png',
        type: 'Lendária',
        buffs: { taijutsu: -10, ninjutsu: 70, genjutsu: 0, selo: 10, vitalidade: -20, inteligencia: 20 },
        requiredLevel: 65,
        price: 60000,
    },
    {
        id: 'ryuuga_garian_tou',
        name: 'Ryūga Garian Tō',
        description: 'A lendária "Espada do Dragão Faminto" forjada nas chamas de um dragão ancestral. Sua lâmina emana um calor intenso capaz de incinerar qualquer coisa que toque. Dizem que apenas aqueles com vontade de ferro podem empunhá-la sem serem consumidos por sua fúria flamejante.',
        imageUrl: 'https://i.ibb.co/fdStn4P1/Ryuuga-Garian-Tou.png',
        type: 'Lendária',
        buffs: { taijutsu: 35, ninjutsu: 45, genjutsu: 0, selo: 20, vitalidade: 10, inteligencia: -5 },
        requiredLevel: 68,
        price: 80000,
    },
    {
        id: 'hiraishin_kunai',
        name: 'Hiraishin Kunai',
        description: 'A kunai especial de três pontas marcada com a fórmula do Jutsu Deus Voador do Trovão. Criada por Minato Namikaze, permite teletransporte instantâneo para quem domina a técnica. Sua lâmina é mais resistente que kunais comuns e a marca de selamento nunca desaparece.',
        imageUrl: 'https://i.ibb.co/xtmrWrWD/Hiraishin-Kunai.png',
        isPremium: true,
        type: 'Ferramenta Ninja',
        buffs: { taijutsu: 20, ninjutsu: 35, genjutsu: 0, selo: 60, vitalidade: 0, inteligencia: 25 },
        requiredLevel: 70,
        price: 90000,
    },
    {
        id: 'kohaku_no_johei',
        name: 'Pote Purificador de Brasas',
        description: 'Uma das ferramentas do Sábio dos Seis Caminhos. Um pote gigante que pode selar qualquer coisa se o alvo responder ao chamado.',
        imageUrl: 'https://i.ibb.co/Xxrghw9k/kohaku-no-johei.png',
        isPremium: true,
        type: 'Lendária',
        buffs: { taijutsu: -20, ninjutsu: 0, genjutsu: 0, selo: 100, vitalidade: 20, inteligencia: 20 },
        requiredLevel: 75,
        price: 120000,
    }
];